# **مجموعه داده:**

*بخش اول:*
---
# پاسخ خود را اینجا بنویسید:

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
دو دیتاست فارسی و انگلیسی دارای ستون‌هایی هستند که در فرایند آموزش نیازی به آنها نیست. علاوه براین این ستون‌ها با هم متفاوت هستند که ادغام دو دیتاست را با هم دچار مشکل می‌کنند.
<br>
همچنین توکن‌ها از جنس کلمه هستند در حالیکه برای آموزش بهتر مدل بهتر است از جنس sub word باشند.
<br>
در نهایت از آنجا که دیتاست‌ها باید با هم ادغام شوند لازم است ویژگی‌های ستون‌های مشترک از یک نوع باشند تا هنگام ادغام به ارور بر نخوریم.
<br>
همچنین لازم است قبل از حذف ستون‌های اضافی لیبل‌ها و id آنها برای محاسبه loss ذخیره شوند.

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
<br>
برای حل مشکل اول ستون‌های اضافی از دو دیتاست حذف و برای رفع مشکل دوم مقدار is_split_into_words در توکنایزر pretrain شده برابر با True قرار داده می‌شود.  همچنین برای تبدیل ویژگی‌های ستون‌های مشترک در دو دیتاست  به یک فرمت از cast استفاده می‌کنیم.

In [ ]:
#write your code here
from datasets import load_dataset
import transformers

persian_dataset = load_dataset("AliFartout/PEYMA-ARMAN-Mixed")
english_dataset =  load_dataset("conll2003", trust_remote_code=True)

In [ ]:
import pandas as pd

persian_dataset['train'].to_pandas().head()

,tokens,ner_tags,ner_tags_names
0,"[یوکوویچ, متولد, دانمارک, است, اما, والدین, او...","[5, 20, 1, 20, 20, 20, 20, 1, 20, 20]","[B_PER, O, B_LOC, O, O, O, O, B_LOC, O, O]"
1,"[0, خانواده, ایرانی, از, اوکی, هارو, یاسوائوکا...","[20, 20, 20, 20, 5, 12, 12, 20, 3, 10, 20, 20,...","[O, O, O, O, B_PER, I_PER, I_PER, O, B_ORG, I_..."
2,"[وي, با, بیان, این, كه, قرار, شد, خبرگان, ملت,...","[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 2...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,"[به, گزارش, ایسنا, ،, اطهره, نژادی, معاون, هما...","[20, 20, 3, 20, 5, 12, 20, 20, 20, 20, 3, 10, ...","[O, O, B_ORG, O, B_PER, I_PER, O, O, O, O, B_O..."
4,"[به, گزارش, خبرنگار, پارلمانی, ایسنا, ،, ترکیب...","[20, 20, 20, 20, 3, 20, 20, 20, 3, 10, 10, 10,...","[O, O, O, O, B_ORG, O, O, O, B_ORG, I_ORG, I_O..."

In [ ]:
english_dataset['train'].to_pandas().head()

,id,tokens,pos_tags,chunk_tags,ner_tags
0,0,"[EU, rejects, German, call, to, boycott, Briti...","[22, 42, 16, 21, 35, 37, 16, 21, 7]","[11, 21, 11, 12, 21, 22, 11, 12, 0]","[3, 0, 7, 0, 0, 0, 7, 0, 0]"
1,1,"[Peter, Blackburn]","[22, 22]","[11, 12]","[1, 2]"
2,2,"[BRUSSELS, 1996-08-22]","[22, 11]","[11, 12]","[5, 0]"
3,3,"[The, European, Commission, said, on, Thursday...","[12, 22, 22, 38, 15, 22, 28, 38, 15, 16, 21, 3...","[11, 12, 12, 21, 13, 11, 11, 21, 13, 11, 12, 1...","[0, 3, 4, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, ..."
4,4,"[Germany, 's, representative, to, the, Europea...","[22, 27, 21, 35, 12, 22, 22, 27, 16, 21, 22, 2...","[11, 11, 12, 13, 11, 12, 12, 11, 12, 12, 12, 1...","[5, 0, 0, 0, 0, 3, 4, 0, 0, 0, 1, 2, 0, 0, 0, ..."

# **سوال اول:**

*بخش اول:*
---
# پاسخ خود را اینجا بنویسید:
‌
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
در بخش اول لیستی از لیبل‌های موجود در دیتاست تعریف می‌شود و به کمک این لیست  دیکشنری id2label شامل id لیبل‌ها و خود لیبل‌ها برای محاسبات بعدی ایجاد می‌شود (محاسبه loss).
<br>
در بخش دوم ستون‌های اضافی و غیرمشترک بین دو دیتاست از هر دیتاست حذف می‌شوند
<br>.
در بخش سوم ویژگی‌های ستون ner_tag دیتاست انگلیسی با ویژگی‌های ستون ner_tag دیتاست فارسی با استفاده از cast هم فرمت می‌شون
<br>د.
درنهایت دیتاست‌های train، validation و test هر دو دیتاست با هم concat می‌شوند.

In [ ]:
#write your code here

labels = persian_dataset["train"].features["ner_tags"].feature.names

id2label = {idx: label for idx, label in enumerate(labels)}

print("# labels:", len(labels))
print("id2label:", id2label)

# labels: 21
id2label: {0: 'B_LOC', 1: 'I_DAT', 2: 'B_PCT', 3: 'I_LOC', 4: 'I_PER', 5: 'I_MON', 6: 'B_ORG', 7: 'B_PRO', 8: 'B_PER', 9: 'O', 10: 'I_PCT', 11: 'I_ORG', 12: 'B_FAC', 13: 'B_DAT', 14: 'B_TIM', 15: 'I_TIM', 16: 'I_EVE', 17: 'B_MON', 18: 'I_PRO', 19: 'B_EVE', 20: 'I_FAC'}

#### remove unnecessary columns from both datasets

In [ ]:
persian_dataset['train'] = persian_dataset['train'].remove_columns(['ner_tags_names'])
persian_dataset['validation'] = persian_dataset['validation'].remove_columns(['ner_tags_names'])
persian_dataset['test'] = persian_dataset['test'].remove_columns(['ner_tags_names'])

persian_dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 26384
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 3296
    })
    test: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 3296
    })
})

In [ ]:
english_dataset['train'] = english_dataset['train'].remove_columns(['pos_tags', 'chunk_tags', 'id'])
english_dataset['validation'] = english_dataset['validation'].remove_columns(['pos_tags', 'chunk_tags', 'id'])
english_dataset['test'] = english_dataset['test'].remove_columns(['pos_tags', 'chunk_tags', 'id'])

english_dataset

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['tokens', 'ner_tags'],
        num_rows: 3453
    })
})

#### cast 'ner_tags' column of english_dataset with 'ner_tags' column of persian_dataset

In [ ]:
english_dataset = english_dataset.cast_column('ner_tags', persian_dataset['train'].features['ner_tags'])

Casting the dataset:   0%|          | 0/14041 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/3250 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/3453 [00:00<?, ? examples/s]

#### concatenate datasets

In [ ]:
from datasets import concatenate_datasets

train_dataset = concatenate_datasets([persian_dataset['train'], english_dataset['train']])
val_dataset = concatenate_datasets([persian_dataset['validation'], english_dataset['validation']])
test_dataset = concatenate_datasets([persian_dataset['test'], english_dataset['test']])

*بخش دوم:*
---
# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
همانطور که در بخش اول اشاره شد توکن‌ها از جنس کلمه هستند در حالیکه برای آموزش باید از جنس sub word باشند. که برای رفع این مشکل توکن‌ها باید دوباره به sub word توکنایز شوند. این توکنایز دوباره باعث عدم تطابق بین ورودی و لیبل‌ها می‌شود. زیرا یک کلمه واحد مربوط به یک لیبل واحد اکنون ممکن است به دو زیر کلمه تقسیم شود. همچنین توکنایزر XLMRoberta دو توکن [<s>] و [</s>] را به ‌توکن‌های موجود بعد از توکنایز کردن در سطح sub word اضافه می‌کند که باید به این توکن‌ها نیز لیبلی اختصاص داد.
<br>
برای رفع این مشکل باید
<br>:
1.	‏همه توکن‌های sub word به کلمه مربوطه‌شان با استفاده از متد ‏word_ids نگاشت شون
<br>د
2.	سپس برای ایجاد انسجام در لیبل‌ها و جلوگیری از redundancy تنها به اولین توکن sub word کلمه لیبل کلمه اختصاص داده می‌شود . به بقیه sub word های کلمه لیبل -100 اختصاص داده می‌ش
<br>و
3.	‏اختصاص لیبل -100 به توکن‌[<ها]ی s[> و ]</s>. زیرا مقدار لیبل منفی توسط تابع loss PyTorch نادیده گرفته می‌شود.

## توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
برای alignment تابع tokenize_and_align_labels تعریف شده‌است. در این تابع ابتدا توکن‌ها در به ازای هر نمونه مجموعه داده که به صورت کلمه هستند با استفاده از توکنایزر XLMRobert و با قرار دادن مقدار True برای is_split_into_words به sub word تقسیم می‌شوند، همانطور که قبلا بیان شد توکنایزر XLMRobert دو توکن جدید > و </s> را به ‌توکن‌های موجود بعد از توکنایز کردن اضافه می‌کند. با تعریف یک حلقه for بر روی مقادیر ستون ner_tags به ازای هر نمونه‌ ابتدا به کمک متد word_ids آی دی کلمات معادل هر کدام از sub word ها تعریف می‌شود. سپس متغیر previous_word_idx ( برای اینکه تنها به اولین توکن sub word کلمه لیبل کلمه اختصاص داده ‌شود، استفاده خواهد شد) و لیست label_ids (برای ذخیره لیبل‌های جدید برای توکن‌های جدید به ازای هر نمونه)  تعریف می‌شوند.
<br>
با iterate بر روی word_ids توکن‌ها، اگر مقدار word_id توکن برابر با None باشد یعنی آن توکن یکی از دو توکن جدید اضافه شده توسط توکنایزر است، پس لیبل -100 را خواهد گرفت. اگر word_id آن توکن برابر با word_id توکن قبلی نباشد یعنی دو توکن متعلق به یک کلمه نیستند، پس لیبل آن کلمه به عنوان لیبل آن توکن ذخیره خواهد شد. در نهایت اگر word_id آن توکن برابر با word_id توکن قبلی باشد یعنی هر دو توکن متعلق به یک کلمه هستند و از آنجا که قرار است تنها توکن اول کلمه لیبل کلمه را بگیرد، این توکن دیگر کلمه لیبل -100 خواهد گرفت. در نهایت ner_tags جدید برای آن نمونه در لیست labels ذخیره می‌شود. این تابع با استفاده از متد map بر روی سه دیتاست train، test و validation اعمال می‌شود.
<br>
همچنین با استفاده از ‏‏Data Collator‏‏، batch ای از نمونه ها ایجاد می‌شود تا تعداد توکن‌های هر نمونه را به صورت ‏‏پویا‏‏ به طولانی ترین طول تعداد توکن‌ها در یک batch برساند، به جای اینکه کل دیتاست را به  اندازه حداکثر طول تعداد توکن‌های pad کند.‏

In [ ]:
from transformers import XLMRobertaTokenizerFast

tokenizer = XLMRobertaTokenizerFast.from_pretrained("xlm-roberta-base")

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)

    labels = []
    for i, label in enumerate(examples[f"ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

In [ ]:
train_dataset = train_dataset.map(tokenize_and_align_labels, batched=True)
val_dataset = val_dataset.map(tokenize_and_align_labels, batched=True)
test_dataset = test_dataset.map(tokenize_and_align_labels, batched=True)

Map:   0%|          | 0/40425 [00:00<?, ? examples/s]

Map:   0%|          | 0/6546 [00:00<?, ? examples/s]

Map:   0%|          | 0/6749 [00:00<?, ? examples/s]

In [ ]:
print(train_dataset)

Dataset({
    features: ['tokens', 'ner_tags', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 40425
})

In [ ]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

#### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
برای TokenClassifiaction با استفاده از xlmRoberta کلاس xlmRobertaSequenceClassification تعریف شده‌است. در این کلاس ابتدا لایه‌های مدل که شامل xlmRoberta،  dropout (برای جلوگیری از overfiting) و linear (برای طبقه‌بندی) که سایز ورودی آن به اندازه سایز آخرین لایه hidden مدل xlmRoberta  و سایز خروجی به اندازه تعداد لیبل‌ها است، هستند، تعریف می‌شوند.
<br>
در قسمت forward، id توکن‌ها و attention mask به عنوان ورودی به مدل xlmRoberta داده می‌شوند و آخرین لایه پنهان مدل به عنوان خروجی تعریف می‌شود. سپس خروجی به لایه dropout برای جلوگیری از overfitting داده می‌شود و خروجی این لایه به لایه linear برای طبقه بندی و تولید logit ها داده می‌شوند
<br>.
برای محاسبه loss اگر لیبل وجود داشته باشد ابتدا تابع loss تعریف می‌شود. سپس ایندکس attention mask هایی که مقداری برابر با 1 دارند (pad نیستند) ذخیره می‌شود تا براساس آن loss برای مقادیر غیر pad محاسبه شود. در گام بعد logit ها و لیبل‌های active (غیر pad) برای محاسبه loss، flat  می‌شوند و loss محاسبه می‌شود. در نهایت باتوجه به اینکه مقدار gradient_checkpointing در تعریف argument های آموزش مدل True تعریف می‌شود، در این کلاس gradient checkpointing برای مدل فعال می‌شو
<br>د.
در بخش بعد TrainingArguments مشابه آنچه در صورت سوال داده شده تعریف می‌ش
<br>
برای محاسبه معیارهای خواسته شده متریک seqeval به کمک کتابخانه evaluate بارگذاری می‌شود. سپس تابع compute_metrics تعریف شده که ورودی‌های آن پیش‌بینی مدل و لیبل‌های اصلی ‌توکن‌ها (به صورت id) است. پیش‌بینی مدل به صورت logit هستند که  با استفاده از تابع argmax به id لیبل تبدیل می‌شوند. با iterate بر روی پیش‌بینی مدل و لیبل‌های اصلی ‌توکن‌ها بررسی می‌شود اگر مقدار لیبل برابر با -s>) نباشد، id ها به لیبل با استفاده از دیکشنری id2label که در بخش قبل ایجاد شد تبدیل می‌شوند. سپس به کمک لیبل‌های ایجاد شده معیارهای خواسته شده محاسبه و برگردانده می‌شوند.
<br>
در نهایت trainer برای آموزش مدل با تعریف پارامترها شامل مدل، آرگومان‌های آموزش، داده‌های آموزش و ارزیابی، compute_metrics و data_collator تعریف می‌شود و مدل آموزش داده می‌شود.ود.

In [ ]:
 #write your code here
import torch
import torch.nn as nn
from transformers import XLMRobertaModel


class xlmRobertaSequenceClassification(nn.Module):
    def __init__(self, num_labels):
        super(xlmRobertaSequenceClassification, self).__init__()

        self.xlmRoberta = XLMRobertaModel.from_pretrained("xlm-roberta-base")
        self.dropout = nn.Dropout(self.xlmRoberta.config.hidden_dropout_prob)
        self.linear = nn.Linear(self.xlmRoberta.config.hidden_size, num_labels)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.xlmRoberta(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = outputs.last_hidden_state

        sequence_output = self.dropout(sequence_output)
        logits = self.linear(sequence_output)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            active_loss = attention_mask.view(-1) == 1
            active_logits = logits.view(-1, logits.shape[-1])[active_loss]
            active_labels = labels.view(-1)[active_loss]
            loss = loss_fct(active_logits, active_labels)

        return {'loss': loss, 'logits': logits} if loss is not None else logits

    def gradient_checkpointing_enable(self, **kwargs):
        self.xlmRoberta.gradient_checkpointing_enable()


model = xlmRobertaSequenceClassification(num_labels=21)

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
output_dir="Roberta-fa-en-ner",
report_to="none", log_level="error",
num_train_epochs=1,
gradient_checkpointing=True,
eval_accumulation_steps=10,
per_device_train_batch_size=24,
per_device_eval_batch_size=24,
seed=42,
logging_strategy="steps", eval_strategy="steps",
save_steps=1e6, weight_decay=0.01, disable_tqdm=False,
logging_steps=1e6, eval_steps=400, push_to_hub=False)

In [ ]:
pip install evaluate seqeval

/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: datasets>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (3.1.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /opt/conda/lib/python3.10/site-packages (from evaluate) (4.66.4)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.10/site-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /opt/conda/lib/python3.10/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from evaluate) (0.26.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from evaluate) (21.3)
Requirement already satisfied: scikit-learn>=0.21.3 in /opt/conda/lib/python3.10/site-packages (from seqeval) (1.2.2)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.15.1)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (17.0.0)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (3.9.5)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->evaluate) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.19.0->evaluate) (2024.6.2)
Requirement already satisfied: scipy>=1.3.2 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (1.14.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.21.3->seqeval) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 4.1 MB/s eta 0:00:00
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16161 sha256=4cc13dee14c6dc0d012f1b43b30f8bb2645ff3ec4c209bb92ec3e42875f6b319
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval
Installing collected packages: seqeval, evaluate
Successfully installed evaluate-0.4.3 seqeval-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import evaluate
import numpy as np

metric = evaluate.load("seqeval")

def compute_metrics(eval_pred):
    predictions, references = eval_pred

    predictions = np.argmax(predictions, axis=2)

    filtered_predictions = []
    filtered_references = []

    for preds, refs in zip(predictions, references):
        filtered_preds = []
        filtered_refs = []
        for p, r in zip(preds, refs):
            if r != -100:
                filtered_preds.append(id2label[p])
                filtered_refs.append(id2label[r])
        filtered_predictions.append(filtered_preds)
        filtered_references.append(filtered_refs)

    results = metric.compute(predictions=filtered_predictions, references=filtered_references)

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

Downloading builder script:   0%|          | 0.00/6.34k [00:00<?, ?B/s]

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator
)

In [ ]:
trainer.train()

/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_FAC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_LOC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PCT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PER seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_ORG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_MON seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_DAT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PRO seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PER seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_FAC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PCT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_EVE seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_TIM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_TIM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_LOC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PRO seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_EVE seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_MON seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_ORG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_DAT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

TrainOutput(global_step=1685, training_loss=0.12374195132835683, metrics={'train_runtime': 776.3126, 'train_samples_per_second': 52.073, 'train_steps_per_second': 2.171, 'total_flos': 0.0, 'train_loss': 0.12374195132835683, 'epoch': 1.0})

*بخش سوم:*
---
# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
برای ارزیابی مدل بر روی داده‌های تست، trainer.eval_dataset را که موقع آموزش برابر با validation dataset بود، برابر با test dataset قرار میدهیم و عملکرد مدل بر روی داده‌های تست با استفاده از معیارهای precision، recall، F1 و accuracy نشان داده می‌شود.
<br>
اگر فراوانی لیبل‌ها به صورت نامتوازن باشد، دقت به تنهایی معیاری خوبی برای بررسی عملکرد مدل نیست. همچنین دقت تنها تعداد پیش‌بینی‌های صحیح را در نظر می‌گیرد و تفاوتی بین خطای نوع اول (False Positive) و خطاهای نوع دوم (False Negative) قائل نمی‌شود. که در برخی کاربردها، نوع خطاها اهمیت بیشتری دارد.

In [ ]:
#write your code here

trainer.eval_dataset = test_dataset
results_test = trainer.evaluate()
print(results_test)

/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_MON seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_FAC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_LOC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_DAT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_FAC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PER seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PCT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_LOC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PRO seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PRO seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_EVE seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_MON seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_EVE seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_TIM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_TIM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_PER seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: I_ORG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_ORG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_DAT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/opt/conda/lib/python3.10/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: B_PCT seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))

{'eval_loss': 0.08073244988918304, 'eval_precision': 0.9441863355967494, 'eval_recall': 0.9518625270215232, 'eval_f1': 0.9480088927025234, 'eval_accuracy': 0.9795368125389191, 'eval_runtime': 25.9237, 'eval_samples_per_second': 260.341, 'eval_steps_per_second': 10.878, 'epoch': 1.0}

### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
برای نمایش خروجی مدل آموزش داده شده بر روی یک نمونه دلخواه، یک نمونه دلخواه از داده‌های تست انتخاب می‌شود ( قبلا توکن‌های داده‌های تست به sub word تبدیل شدند و aligment بر روی داده‌های تست نیز انجام شده‌است). device تعریف می‌شود و مدل به device منتقل می‌شود. همچنین مقادیر ستون‌های مورد نیاز برای محاسبات بعدی برای این نمونه به تنسور تبدیل شده و به device منتقل می‌شوند. مدل در حالت eval قرار گرفته و محاسبه گرادیان متوقف می‌شود. سپس خروجی مدل به ازای مقادیر دو ستون input_ids و attention_mask این نمونه محاسبه می‌شود. با argmax گرفتن بر روی خروجی مدل لیبل‌های پیش‌بینی شده بدست می‌آیند. اما این لیبل‌ها به ازای هر sub word هستند در حالیکه ما لیبل هر word را می‌خواهیم. بنابراین با iterate بر روی لیبل‌های اصلی و پیش‌بینی شده اگر مقدار لیبل اصلی مخالف -100 باشد، مقادیر دو گروه لیبل ذخیره می‌شود. در نهایت جمله، ner_tags های پیش‌بینی شده و اصلی به ازای هر کلمه  جمله نمایش داده می‌شوند.

In [ ]:
inputs = test_dataset[3500]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

inputs = {
    key: torch.tensor(value).unsqueeze(0).to(device)
    for key, value in inputs.items()
    if key in ["input_ids", "attention_mask", "labels"]
}


model.eval()

with torch.no_grad():
    logits = model(input_ids=inputs["input_ids"], attention_mask=inputs["attention_mask"])


predictions = torch.argmax(logits, dim=2).squeeze(0)
labels = inputs["labels"].squeeze(0)


filtered_predictions = []
filtered_references = []

for p, r in zip(predictions, labels):
    if r != -100:
        filtered_predictions.append(id2label[p.item()])
        filtered_references.append(id2label[r.item()])


print("Sentence:", " ".join(test_dataset[3500]["tokens"]))
print("\nPredicted NER tags:", filtered_predictions)
print("\nReference NER tags:", filtered_references)

Sentence: GOLF - ZIMBABWE OPEN SECOND ROUND SCORES .

Predicted NER tags: ['B_LOC', 'B_LOC', 'B_PRO', 'B_PER', 'B_LOC', 'B_LOC', 'B_LOC', 'B_LOC']

Reference NER tags: ['B_LOC', 'B_LOC', 'B_PRO', 'B_PER', 'B_LOC', 'B_LOC', 'B_LOC', 'B_LOC']

# **سوال دوم:**

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
سوالات خودتان را می‌توانید از طریق ایمیل
<code>mohamadgorjicode@gmail.com</code>
 از طراح تمرین 4 برای سوال دوم بپرسید.

# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ابتدا باید کتابخانه‌ dataset hugging face را نصب کرد. سپس با استفاده از load_dataset این کتابخانه می‌توان مجموعه داده موردنظر را بارگذاری کرد.
    
<br>
<br>
مفاهیم:
<br>
بله نیاز است که وردی به صورت prompt تعریف شود که در آن علاوه بر ورودی تسک مورد نظر ذکر می شود. به عنوان مثال قبل از مقاله ورودی “summarize the article” نیز اضافه می شود. سپس prompt تولید شده باید توکنایز شود تا به فرمت مناسب به عنوان وردی مدل تبدیل گردد.

### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ابتدا کتابخانه های موردنیاز import می‌شوند. سپس نسخه 3 دیتاست بارگذاری می‌شود و اطلاعات آن چاپ می‌شود. از هر کدام از سه دیتاست تعدادی نمونه پس از shuffle کردن نمونه‌ها انتخاب می‌شود و دیکشنری دیتاست جدیدی برای دیتاست با تعداد نمونه‌ی کمتر ایجاد می‌شود. در نهایت اطلاعات دیتاست جدید چاپ می‌شود.
<br>
در بخش بعد یک نمونه از مقاله و خلاصه آن چاپ می‌شود.
<br>
در قسمت بعد تابعی برای محاسبه کوتاه ترین، بلندترین و میانگین طول‌های مقالات و خلاصه‌ها تعریف شده‌است. در این تابع ابتدا لیستی شامل طول هر مقاله و لیستی دیگری شامل طول‌های هر خلاصه ایجاد می‌شود. با min، max و میانگین گرفتن از این لیست‌ها موارد خواسته شده بدست می‌آید و چاپ می‌شوند.

In [4]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.27.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [5]:
#write your code here

from datasets import load_dataset, DatasetDict

dataset = load_dataset("cnn_dailymail", "3.0.0")

print(dataset)

train_dataset = dataset["train"].shuffle(seed=42).select(range(5000))
val_dataset = dataset["validation"].shuffle(seed=42).select(range(500))
test_dataset = dataset["test"].shuffle(seed=42).select(range(100))

dataset_dict = DatasetDict({
    "train": train_dataset,
    "validation": val_dataset,
    "test": test_dataset
})


print(dataset_dict)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})
DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 5000
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 500
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 100
    })
})

In [ ]:
print("article:", dataset_dict["train"][0]["article"])
print("summary:", dataset_dict["train"][0]["highlights"])

article: By . Anthony Bond . PUBLISHED: . 07:03 EST, 2 March 2013 . | . UPDATED: . 08:07 EST, 2 March 2013 . Three members of the same family who died in a static caravan from carbon monoxide poisoning would have been unconscious 'within minutes', investigators said today. The bodies of married couple John and Audrey Cook were discovered alongside their daughter, Maureen, at the mobile home they shared on Tremarle Home Park in Camborne, west Cornwall. The inquests have now opened into the deaths last Saturday, with investigators saying the three died along with the family's pet dog, of carbon monoxide poisoning from a cooker. Tragic: The inquests have opened into the deaths of three members of the same family who were found in their static caravan last weekend. John and Audrey Cook are pictured . Awful: The family died following carbon monoxide poisoning at this caravan at the Tremarle Home Park in Camborne, Cornwall . It is also believed there was no working carbon monoxide detector in the static caravan. Cornwall Fire and Rescue Service said this would have resulted in the three being unconscious 'within minutes', . A spokesman for Cornwall coroner Dr Emma Carlyon confirmed the inquests were opened and adjourned yesterday afternoon. They will resume at a later date. Devon and Cornwall Police confirmed on Monday that carbon monoxide poisoning had been established as the cause of death. A police spokesman said the source of the poisoning was 'believed to be from incorrect operation of the gas cooker'. Poisoning: This woman left flowers outside the caravan following the deaths. It has emerged that the trio would have been unconscious 'within minutes' Touching: This tribute was left outside the caravan following news of the deaths . Early readings from experts at the site revealed a potentially lethal level of carbon monoxide present within the caravan at the time it was taken, shortly after the discovery of the bodies. Friends and neighbours have paid tribute to the trio. One . neighbour, Sonya Owen, 53, said: 'It's very distressing. I knew the . daughter, she was living her with her mum and dad. Everybody is really . upset.' Margaret Holmes, 65, who lived near the couple and their . daughter, said: 'They had lived here for around 40 years and they kept . themselves to themselves. 'I just can’t believe this has . happened, it is so sad and I am so shocked, I think we all are, you just . don’t expect this sort of thing to happen on your doorstep. 'Everyone will miss them, we used to chat a lot when we were both in the garden. 'I would just like to send my condolences to their family, I can’t imagine what they’re going through.' Nic Clark, 52, who was good friends with daughter Maureen, added: 'They were a lovely kind family, a great trio. 'Maureen . used to go out and walk her dog, a little Jack Russell, it is so sad . what has happened, I understand the dog went with them. 'They . will be sorely missed and I think everyone is just in shock at the . moment, I would like to send my condolences to the Cook family.'
summary: John and .
Audrey Cook were discovered alongside their daughter, Maureen .
They were found at Tremarle Home Park in Cornwall .
Investigators say the three died of carbon monoxide .
poisoning .

In [ ]:
def calculate_lengths(dataset, text_column, summary_column):
    text_lengths = [len(sample[text_column].split()) for sample in dataset]
    summary_lengths = [len(sample[summary_column].split()) for sample in dataset]

    min_text_length = min(text_lengths)
    max_text_length = max(text_lengths)
    avg_text_length = sum(text_lengths) / len(text_lengths)

    min_summary_length = min(summary_lengths)
    max_summary_length = max(summary_lengths)
    avg_summary_length = sum(summary_lengths) / len(summary_lengths)

    return (min_text_length, max_text_length, avg_text_length), (min_summary_length, max_summary_length, avg_summary_length)

text_stats, summary_stats = calculate_lengths(dataset_dict["train"], "article", "highlights")

print("article- min:", text_stats[0], "max:", text_stats[1], "mean:", text_stats[2])
print("summary- min:", summary_stats[0], "max:", summary_stats[1], "mean:", summary_stats[2])

article- min: 37 max: 1924 mean: 690.0122
summary- min: 6 max: 362 mean: 51.123

*بخش اول:*
---
# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
 مفهوم یک:
 <br>
 معیارهایی مانند ROUGE  معمولاً بر اساس تطبیق کلمه عمل می‌کنند، که باعث ناتوانی در درک معنای واقعی جملات و حساسیت به تفاوت‌های کوچک در ساختار زبانی می شود. معیارهایی مانند BERTScore که بر اساس contextual embedding  ها کار می‌کنند، می‌توانند معنای جملات را بهتر درک کنند، اما به پردازش بیشتری نیاز دارند و محاسبات سنگین‌تری دارند و گاهی contextual embedding های معنای متن را نادرست تفسیر می‌کنند.
همچنین ارزیابی انسجام و یکنواختی متن تولیدشده پیچیده است. زیرا متن ممکن است از نظر گرامری درست باشد، اما از لحاظ معنایی دچار تناقض یا پراکندگی شود. متن‌های تولیدشده گاهی بسیار تکراری می‌شوند. تعیین این‌که یک متن تنوع کافی دارد یا تکرار بیش از حد ندارد، هم با معیارهای خودکار و هم انسانی چالش‌برانگیز است.
علاوه بر این بسیاری از جنبه‌های کیفی متن، مانند خلاقیت، سبک و میزان جذابیت، تنها از طریق ارزیابی انسانی قابل سنجش هستند. که ارزیابی انسانی زمان‌بر، پرهزینه و مستعد سوگیری است.
از دیگر چالش ها می توان به این مساله اشاره کرد که کیفیت متن بدون توجه به کاربرد آن چالش‌برانگیز است. زیرا کیفیت یک متن به کاربرد خاص آن بستگی دارد، مثلا یک متن خبری باید دقیق و مختصر باشد و یک متن داستانی باید خلاقانه و جذاب باشد.
همچنین در ارزیابی خودکار، مدل معمولاً با یک متن مرجع مقایسه می‌شود. اما متون مرجع ممکن است ناقص یا دارای سوگیری باشند.
    
<br>
<br>
مفهوم 2:
    <br>
مجموعه‌ای از معیارهای ارزیابی است که بر اساس تطابق   n-gram‌ها، عبارات، یا توالی‌ها بین متن تولیدشده (خلاصه مدل) و متن مرجع کار می‌کند. این معیار دارای انواعی است که شامل:
    <br>
1.	ROUGE-N: مقایسه n-gramهای مشترک بین خلاصه‌ها  (مانند ROUGE-1 برای تک‌کلمات و ROUGE-2 برای جفت‌کلمات).
    <br>
2.	ROUGE-L  استفاده از طولانی‌ترین زیررشته مشترک (Longest Common Subsequence - LCS) بین خلاصه‌ها.
    <br>
3.	ROUGE-W: نسخه وزنی از ROUGE-L که برای تطابق‌های پیوسته وزن بیشتری در نظر می‌گیرد.
    <br>
از مزایا این معیار سادگی و سرعت برای داده‌های بزرگو  بر اساس شباهت‌های سطحی متن عمل می‌کند و برای مقایسه واژگان مناسب است. و از معایب آن عدم درک معنایی است یعنی اگر کلمات مترادف یا ساختارهای متفاوت ولی معنای مشابه استفاده شوند، ROUGE  قادر به تشخیص نیست. همچنین کوچک‌ترین تغییرات زبانی باعث کاهش امتیاز می‌شودو  ساختار و انسجام کلی متن را بررسی نمی‌کند.
    <br>
این معیار مناسب برای ارزیابی ساختار سطحی (لغوی) خلاصه‌ها است و وقتی خلاصه‌ها باید کاملاً شبیه به متن مرجع باشند، ROUGE  بهتر عمل می‌کند.
<br>
    <br>
BERTScore یک معیار معنایی است که از مدل‌های زبانی پیشرفته مثل BERT  استفاده می‌کند. نحوه کارکرد این معیار به اینصورت است که هر کلمه در متن تولیدشده و متن مرجع به یک embedding  تبدیل می‌شود و شباهت معنایی این embedding ها اندازه‌گیری می‌شود و تطابق معنایی بین کلمات دو متن، با وزن‌دهی به ترتیب آن‌ها محاسبه می‌گردد.
    <br>
از مزایای این معیار می‌توان به این موارد اشاره کرد که توانایی تشخیص مترادف‌ها و جملاتی با ساختار متفاوت ولی معنای مشابه را دارد، به جای تطابق ساده واژگان، معنای کلی متن را می‌سنجدو  به کمک مدل‌های زبانی عملکرد بهتری برای متون پیچیده دارد.
    <br>
و از معایب آن سنگین بودن محاسبات است زیرا  نیاز به پردازش زیاد و استفاده از مدل‌های زبانی بزرگ دارد،همچنین  کیفیت آن به کیفیت و تنوع داده‌های آموزشی مدل زبانی بستگی دارد و دارای کاهش دقت در زبان‌های کم‌منبع است در حالیکه عملکرد بهتری در زبان‌های پرکاربرد (مثل انگلیسی) دارد.
    <br>
این معیار مناسب برای ارزیابی خلاصه‌هایی که تنوع زبانی دارند یا مترادف‌ها استفاده شده است، است و برای سنجش کیفیت معنایی خلاصه‌ها بسیار کارآمد است.
<br>
<br>
برای ارزیابی خلاصه‌سازی متن، بهتر است هر دو معیار به صورت مکمل استفاده شوند زیرا ROUGE  برای بررسی دقت و ساختار لغوی وBERTScore  برای ارزیابی انسجام معنایی و شباهت مفهومی بهتر عمل می کند.
    
<br>
<br>
مفهوم 3:
    <br>
Quantization  یک تکنیک بهینه‌سازی است که برای کاهش اندازه مدل‌های یادگیری عمیق و بهبود سرعت اجرا استفاده می‌شود. در این فرآیند، مقادیر دقیق عددی (مانند 32 بیت یا 16 بیت شناور) به مقادیر با دقت کمتر (مانند 8 بیت یا 4 بیت) نگاشت می‌شوند.
    <br>
این کار باعث کاهش اندازه مدل می‌شود. زیرا نگهداری اعداد 4 بیتی به جای 32 یا 16 بیتی باعث کاهش قابل‌توجه حافظه موردنیاز می‌شود. همچنین باعث افزایش سرعت پردازش زیرا عملیات ریاضی (مانند ضرب و جمع ماتریس‌ها) با اعداد 4 بیتی سریع‌تر انجام می‌شود و برای اجرای مدل‌ها روی دستگاه‌هایی مانند موبایل که منابع محدودی دارند، کوانتایزر 4 بیتی انتخاب مناسبی است.
    <br>
این روش منجر به افزایش سرعت محاسبات می‌شود زیرا اعداد کوچک‌تر نیازمند حافظه کمتری هستند، که باعث بهبود زمان انتقال داده‌ها می‌شود و عملیات‌های محاسباتی مانند ضرب ماتریس‌ها سریع‌تر انجام می‌شوند. ولی باعث کاهش دقت می‌شود زیرا نگاشت اعداد 32 بیتی به 4 بیتی باعث از دست رفتن جزئیاتی می‌شود که در اعداد دقیق‌تر وجود دارد. این پدیده خطای کوانتایزاسیون نامیده می‌شود و در مدل‌های حساس به تغییرات کوچک ترجمه زبان، این کاهش دقت ممکن است قابل‌توجه باشد.
    
<br>
<br>
 مفهوم 4:
 <br>
 نمونه هایی برای سناریوی few shot در مدل های زبانی باید:
     <br>
•	متنوع باشند، یعنی طیف وسیعی از ویژگی‌ها، سبک‌ها، و موضوعات را پوشش دهند تا مدل بتواند بهتر با داده‌های متنوع سازگار شود و generalization آن بهبود یابد
 <br>
•	تا حد امکان بدون نویز و خطا باشند. نمونه‌های دارای نویز می‌توانند باعث گمراهی مدل و کاهش عملکرد آن شوند.
     <br>
•	طول متوسط و پیچیدگی متناسب با وظیفه باشند. زیرا نمونه‌های خیلی ساده یا خیلی پیچیده ممکن است تأثیر مثبتی نداشته باشند.
     <br>
•	ارتباط مستقیم با مسئله‌ی مورد نظر داشته باشند. نمونه‌های نامرتبط می‌توانند باعث کاهش عملکرد مدل شوند.
     <br>
•	بر جنبه‌های مهم مسئله تمرکز داشته باشند و از پرداختن به جزئیات غیرضروری پرهیز کنند.
     <br>
•	توزیع مشابهی با داده‌های آزمایشی یا واقعی داشته باشند.
     <br>
•	بیشترین اطلاعات جدید را به مدل اضافه می‌کنند.
    
<br>
<br>
مفهوم 5:
<br>
 نسخه ساده روی مجموعه داده‌های بزرگ و متنوع آموزش داده شده است و هدف اصلی آن یادگیری بازنمایی‌های عمومی زبان است و هیچ تنظیم خاصی برای وظایف مشخص (مانند خلاصه‌سازی یا پاسخ به دستورات) ندارد. که می‌تواند برای طیف وسیعی از وظایف استفاده شود و نیاز به تنظیم دقیق یا ارائه مثال‌های کافی در Few-Shot دارد. همچنین ممکن است در وظایف خاص مانند خلاصه‌سازی کیفیت کمتری ارائه دهد.
<br>
نسخه‌های instruct_tune  شده‌ مدل علاوه بر داده‌های معمول پیش‌آموزش، با مجموعه‌ داده‌های بزرگی از دستورات و پاسخ‌های مرتبط آموزش داده شده‌اند. این نوع آموزش، مدل را قادر می‌سازد تا به طور مؤثرتری به دستورات کاربر پاسخ دهد و وظایفی مانند خلاصه‌سازی، ترجمه، پاسخ به سؤالات و غیره را با دقت بالاتری انجام دهد. در واقع، این مدل‌ها برای پیروی از دستورات بهینه‌سازی شده‌اند. به دلیل آموزش دستوری، نسخه‌های instruct_tune  شده در وظایف پایین‌دستی (Downstream Tasks) مانند خلاصه‌سازی، عملکرد بهتری نسبت به نسخه‌های ساده دارند. این بهبود عملکرد به خصوص در سناریوهای Zero-Shot و Few-Shot  که داده‌ی آموزشی محدودی در دسترس است، بسیار محسوس است.
<br>
نسخه Instruct-Tune شده بهتر عمل می‌کند زیرا مدل برای فهم و پاسخ به دستورات خلاصه‌سازی بهینه شده است و نیازی به طراحی دقیق Prompt نیست.

In [3]:
!pip install -U bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.45.0-py3-none-manylinux_2_24_x86_64.whl.metadata (2.9 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (2.5.1+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: typing_extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from bitsandbytes) (4.12.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.16.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch->bitsandbytes) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->bitsandbytes) (3.0.2)
Downloading bitsandbytes-0.45.0-py3-none-manylinux_2_24_x86_64.whl (69.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 MB 9.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.45.0

In [4]:
!pip install -U accelerate

Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (1.2.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.27.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.4.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2024.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.10.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2024.12.14)

In [5]:
from huggingface_hub import login

login(token="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")

### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ابتدا کتابخانه های موردنیاز import می‌شوند. سپس configuration ای برای کوانتیزاسیون تعریف می‌شود. که در آن کوانتیزاسیون 4-bit فعال می‌شود. تایپ کوانتیزاسیون، دیتا تایپ مقادیر کوانتیزه شده تعریف می‌شود و امکان کوانتیزه کردن مقادیر کواتیزه شده ممکن می شود.
<br>
سپس مدل llama با configuration تعریف شده برای کوانتیزاسیون بارگذاری می شود. همچنین توکنایزر مدل نیز بارگذاری می‌شود و بررسی می‌شود اگر توکن pad در توکنایزر وجود نداشته باشد، آن را اضافه کند و سپس باتوجه به توکن اضافه شده ماتریس امبدینگ توکن‌ها را برای مدل resize کند.
<br>
در بخش بعد ابتدا کتابخانه های مورد نیاز import می شوند. برای انجام تسک summarization توسط مدل llm نیاز است یک pipeline بر اساس مدل و توکنایزر تعریف شده ایجاد شود. حداکثر طول متن تولید شده 120 توکن تعریف می شود. مقدار sampling برابر با true و از روش top_k با مقدار k برابر با 10 استفاده می‌شود تا متن قطعی تری تولید شود. در گام بعد برای انجام سناریوی zero-shot اولین مقاله در داده ها تست به عنوان ورودی به مدل تعریف می شود. سپس prompt برای خلاصه سازی این ورودی ایجاد می‌شود. Prompt به pipeline ایجاد شده داده می‌شود تا مقاله ورودی خلاصه شود. متن تولید شده و متن اصلی تعریف و چاپ می‌شوند و در نهایت معیارهای خواسته شده برای این نمونه تولید می‌شوند.
<br>
در بخش سناریوی few-shot مشابه بخش قبل اولین مقاله در داده ها تست به عنوان ورودی به مدل برای خلاصه سازی تعریف می‌شود. سپس سه مقاله به صورت رندم از داده های آموزش به عنوان shot ها تعریف می شوند. در گام بعد prompt ایجاد می‌شود که در آن مقاله و خلاصه این سه نمونه به عنوان مثال تعریف می‌شوند و از مدل خواسته می‌شوند خلاصه ورودی تعریف شده را تولید کند. Prompt به pipeline ایجاد شده داده می‌شود تا مقاله ورودی خلاصه شود. متن تولید شده و متن اصلی تعریف و چاپ می‌شوند و در نهایت معیارهای خواسته شده برای این نمونه تولید می‌شوند.

In [6]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype="float16"
)


model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B-Instruct", quantization_config=quantization_config)

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-Instruct")

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': '<pad>'})
    model.resize_token_embeddings(len(tokenizer))

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

`low_cpu_mem_usage` was None, now default to True since model is quantized.

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

In [6]:
pip install rouge-score

Requirement already satisfied: rouge-score in /usr/local/lib/python3.10/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.26.4)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->rouge-score) (4.67.1)

In [7]:
pip install bert-score

Requirement already satisfied: bert-score in /usr/local/lib/python3.10/dist-packages (0.3.13)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.5.1+cu121)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.47.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from bert-score) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from bert-score) (2.32.3)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.10/dist-packages (from bert-score) (4.67.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from bert-score) (3.8.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from bert-score) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->bert-score) (2024.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.0.0->bert-score) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.27.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=3.0.0->bert-score) (0.4.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->bert-score) (3.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->bert-score) (2024.12.14)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.2)

In [ ]:
from transformers import pipeline
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import torch


summarization_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=50,
    do_sample=True,
    top_k = 10
)

# zero shot
text = dataset_dict["test"][0]["article"]


# prompt
prompt = f"{text}\n\nSummary:"
result = summarization_pipeline(prompt)


generated_summary = result[0]['generated_text'].split("Summary:")[-1].strip()
reference_summary = dataset_dict["test"][0]["highlights"]

print("\nGenerated Summary:", generated_summary)
print("\nReference Summary:", reference_summary)

# ROUGE
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
rouge_scores = scorer.score(reference_summary, generated_summary)

print("\nROUGE Scores:")
for key, value in rouge_scores.items():
    print(f"{key}: Precision: {value.precision:.4f}, Recall: {value.recall:.4f}, F1: {value.fmeasure:.4f}")

# BERTScore
P, R, F1 = bert_score([generated_summary], [reference_summary], lang="en", rescale_with_baseline=True)
print("\nBERTScore:")
print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")

Generated Summary: The article discusses the growing momentum of medical marijuana legalization in the US, particularly among younger generations and patients with chronic conditions. It highlights the efforts of politicians, researchers, and advocacy groups to push for federal approval and regulation of marijuana. The article also touches

Reference Summary: CNN's Dr. Sanjay Gupta says we should legalize medical marijuana now .
He says he knows how easy it is do nothing "because I did nothing for too long"

ROUGE Scores:
rouge1: Precision: 0.1111, Recall: 0.1724, F1: 0.1351
rouge2: Precision: 0.0227, Recall: 0.0357, F1: 0.0278
rougeL: Precision: 0.0889, Recall: 0.1379, F1: 0.1081

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.1580, Recall: 0.0322, F1: 0.0958

In [ ]:
text = dataset_dict["test"][0]["article"]

# samples for few shot
num_examples = 3
train_indices = random.sample(range(len(dataset_dict["train"])), num_examples)

examples = [
    {
        "article": dataset_dict["train"][i]["article"],
        "summary": dataset_dict["train"][i]["highlights"]
    }
    for i in train_indices
]


# prompt
prompt = "Some examples of article summarization:\n\n"
for example in examples:
    prompt += f"Article: {example['article']}\nSummary: {example['summary']}\n\n"
prompt += f"Now summarize: \n\nArticle: {text}\n\nSummary:"


result = summarization_pipeline(prompt)

generated_summary = result[0]['generated_text'].split("Summary:")[-1].strip()
reference_summary = dataset_dict["test"][0]["highlights"]


print("\nGenerated Summary:", generated_summary)
print("\nReference Summary:", reference_summary)


# ROUGE
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
rouge_scores = scorer.score(reference_summary, generated_summary)

print("\nROUGE Scores:")
for key, value in rouge_scores.items():
    print(f"{key}: Precision: {value.precision:.4f}, Recall: {value.recall:.4f}, F1: {value.fmeasure:.4f}")


# BERTScore
P, R, F1 = bert_score([generated_summary], [reference_summary], lang="en", rescale_with_baseline=True)
print("\nBERTScore:")
print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")

Generated Summary: The article discusses the growing trend of medical marijuana, particularly among young people and parents. The author notes that there is a revolution in the attitudes of everyday Americans, with 53% favoring legalization of marijuana for medical purposes. The article also highlights

Reference Summary: CNN's Dr. Sanjay Gupta says we should legalize medical marijuana now .
He says he knows how easy it is do nothing "because I did nothing for too long"

ROUGE Scores:
rouge1: Precision: 0.1190, Recall: 0.1724, F1: 0.1408
rouge2: Precision: 0.0244, Recall: 0.0357, F1: 0.0290
rougeL: Precision: 0.0952, Recall: 0.1379, F1: 0.1127

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.1772, Recall: 0.0584, F1: 0.1185

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ROUGE-1 معیاری برای اندازه گیری تعداد unigram های مشترک بین بین خلاصه تولید شده و خلاصه مرجع است. که مقادیرprecision، recall و F1 آن چاپ شده است. در هر دو حالت one-shot و few-shot این مقادیر حول 0.1 است که پایین است و نشان دهنده همپوشانی پایین بین دو خلاصه است. البته برای few-shot کمی بالاتر است.
<br>
ROUGE-2 معیاری برای اندازه گیری تعداد bigram های مشترک بین دو خلاصه است. که مقادیرprecision، recall و F1 آن چاپ شده است.  در هر دو حالت one-shot و few-shot این مقادیر حول 0.03 است که پایین است و کمتر از مقادیر ROUGE-1 ها است. این موضوع نشان می‌دهد که تعداد bigramهای مشترک بسیار محدودتر از تعداد unigramهای مشترک است.
<br>
ROUGE-L معیاری برای اندازه گیری طولانی ترین subsequence مشترک بین دو خلاصه است. که مقادیرprecision، recall و F1 آن چاپ شده است. در هر دو حالت one-shot و few-shot این مقادیر حول 0.1 است که پایین است و نشان دهنده alignment محدود بین دو خلاصه است. البته برای few-shot کمی بالاتر است.
<br>
BERTScore از لحاظ معنایی شباهت بین دو خلاصه اصلی و تولید شده را بررسی می کند. که مقادیرprecision، recall و F1 آن چاپ شده است. در هر دو حالت one-shot و few-shot این مقادیر حول 0.1 است و برای few-shot کمی بالاتر است.
<br>
در هر دو سناریو precision کمی بالاتر است، که نشان دهنده برخی نشانه های تطبیق معنایی بین خلاصه تولید شده و مرجع است. یادآوری recall کم است و نشان می‌دهد که خلاصه تولید شده نتوانسته جزئیات مهم مرجع را در بر بگیرد.
<br>
تقریبا مقدار معیارها در سناریو few-shot کمی بیشتر از معادل آنها در سناریو one-shot است. باتوجه به اینکه مدل در سناریو few-shot نمونه هایی مشاهده می کند این خروجی منطقی است.

*بخش دوم:*
---
# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
 مفهوم یک:
<br>
سناریوهای مناسب برای استفاده از مدل‌های عام منظوره بزرگ (بدون آموزش):
<br>
•	کارهای کلی و عمومی: زمانی که نیاز به انجام کارهای کلی مانند خلاصه‌سازی متن، ترجمه، پاسخ به سوالات عمومی، تولید متن خلاقانه، و غیره است، مدل‌های بزرگ بدون نیاز به تنظیم دقیق، عملکرد خوبی ارائه می‌دهند. این مدل‌ها به دلیل حجم وسیع داده‌هایی که با آن آموزش دیده‌اند، دانش عمومی بالایی دارند و می‌توانند به خوبی با انواع مختلف متن و درخواست‌ها سازگار شوند.
<br>
•	کمبود داده‌های آموزشی: در شرایطی که داده‌های آموزشی کافی برای تنظیم دقیق یک مدل کوچکتر وجود ندارد، استفاده از مدل‌های بزرگ که از قبل با حجم عظیمی از داده‌ها آموزش دیده‌اند، می‌تواند موثر باشد.
<br>
•	کمبود منابع محاسباتی کافی برای آموزش: آموزش یا تنظیم دقیق مدل‌ها نیازمند سخت‌افزار قدرتمند است. اگر چنین منابعی در دسترس نباشد، استفاده از مدل‌های آماده گزینه بهتری است.

<br>
<br>
سناریوهای مناسب برای تنظیم دقیق مدل‌های کوچکتر:
<br>
•	کارهای خاص و تخصصی: زمانی که نیاز به انجام کارهای تخصصی در یک حوزه خاص مانند پزشکی است تنظیم دقیق یک مدل کوچکتر با داده‌های مربوط به آن حوزه می‌تواند عملکرد بسیار بهتری نسبت به مدل‌های بزرگ بدون آموزش ارائه دهد.
<br>
•	بهینه‌سازی برای عملکرد و سرعت: مدل‌های بزرگ معمولاً به منابع محاسباتی بیشتری نیاز دارند و ممکن است سرعت پاسخگویی آن‌ها کمتر باشد. در شرایطی که سرعت و کارایی بسیار مهم است، تنظیم دقیق یک مدل کوچکتر می‌تواند گزینه بهتری باشد.
<br>
•	حفظ حریم خصوصی و امنیت: در برخی موارد، به دلیل مسائل مربوط به حریم خصوصی یا امنیت داده‌ها، نمی‌توان از مدل‌های بزرگ که توسط شرکت‌های دیگر ارائه می‌شوند استفاده کرد. در این شرایط، تنظیم دقیق یک مدل کوچکتر با داده‌های داخلی می‌تواند راه‌حل مناسبی باشد.
<br>
•	کنترل بیشتر بر رفتار مدل: با تنظیم دقیق یک مدل کوچکتر، می‌توانید کنترل بیشتری بر رفتار و خروجی‌های مدل ها داشت و آن را به طور دقیق برای نیازهای خاص خود بهینه کرد.
<br>
•	کاهش هزینه‌ها: استفاده از مدل‌های بزرگ معمولاً هزینه‌برتر است، به خصوص اگر نیاز به استفاده مکرر از آن‌ها باشد. تنظیم دقیق یک مدل کوچکتر می‌تواند به کاهش هزینه‌ها کمک کند.

<br>
<br>
مفهوم 2:
<br>
در FP16 به جای 32 بیت، تنها 16 بیت برای ذخیره اعداد اعشاری استفاده می‌کند. که از تأثیرات استفاده از ان بر کارایی مدل می توان به موارد زیر اشاره کرد:
    <br>
۱. این باعث کاهش مصرف حافظه می‌شود، که امکان استفاده از مدل‌های بزرگ‌تر یا پردازش داده‌های بیشتری را روی یک GPU فراهم می‌کند.
    <br>
۲.  GPUها برای FP16 بهینه‌سازی شده‌اند و عملیات ماتریسی و برداری را سریع‌تر انجام می‌دهند. این منجر به افزایش سرعت آموزش و پیش‌بینی می‌شود.
    <br>
۳. در سیستم‌هایی با محدودیت حافظه، FP16 کمک می‌کند تا مدل‌ها یا داده‌هایی که با دقت FP32 جا نمی‌شوند، قابل استفاده باشند.
    <br>
۴.  البته اعداد FP16 دامنه و دقت کمتری نسبت به FP32 دارند، که ممکن است در محاسبات حساس به دقت، خطاهای عددی ایجاد کند.

<br>
<br>
مفهوم 3:
<br>
SmolLM2 خانواده ای از مدل های زبان فشرده است که در سه اندازه با 135 میلیون، 360 میلیون و 1.7 میلیارد پارامتر موجود است. آنها می توانند طیف گسترده ای از وظایف را حل کنند در حالی که به اندازه کافی سبک هستند تا روی دستگاه اجرا شوند.
    <br>
در مدل‌های 135 میلیون و360 میلیون طراحی مشابهی با MobileLLM به‌کار رفته است که شامل توجه مبتنی بر گروه‌بندی پرسش‌ها (Grouped-Query Attention - GQA) می‌باشد و در آن‌ها عمق مدل بر عرض ترجیح داده شده است.  یعنی در روش استاندارد Attention ، هر توکن در ورودی Queries، Keys و Values  مخصوص به خود را تولید می‌کند و با تمامی توکن‌ها تعامل دارد. ولی در GQA  توکن‌ها به گروه‌هایی تقسیم می‌شوند و یک مجموعه مشترک از Queries برای هر گروه ایجاد می‌شود.
    <br>
مدل‌های SmolLM ابتدا بر روی مجموعه داده‌ای به نام SmolLM-Corpus  آموزش دیده‌اند و پس از پیش‌آموزش، مدل‌ها با استفاده از مجموعه داده‌های عمومی و منتخب به نام Smol Talk  تنظیم دقیق شده‌اند.
    <br>
SmolLM2 پیشرفت های قابل توجهی را نسبت به ورژن قبلی خود یعنی SmolLM1 به ویژه در دنبال کردن دستورالعمل، دانش و استدلال از خود نشان داده است.
مدلSmolLM  (دارای معماری مشابه LlamaForCausalLM) شامل چندین لایه است که به صورت زیر هستند:
    <br>
1.	Embedding Layer  برای تبدیل توکن‌ها به بردارهای تعبیه‌شده.
    <br>
2.	32 لایه Decoder برای پردازش اطلاعات به‌وسیله self attention و لایه های MLP و Rotary Embedding
    <br>
3.	Normalization  برای بهبود همگرایی و عملکرد مدل.
    <br>
4.	Rotary Embedding  برای حفظ ترتیب اطلاعات.
    <br>
5.	LM Head  برای پیش‌بینی توکن‌های خروجی.

   
<br>
<br>
مفهوم 4:
<br>
برای دستیابی به مدل‌های زبانی کوچک با دقت مناسب و بهینه‌سازی عملکرد آن‌ها با منابع محاسباتی محدود، تکنیک‌های متنوعی وجود دارد. این تکنیک‌ها شامل بهینه‌سازی معماری، روش‌های آموزشی، و فشرده‌سازی مدل‌ها می‌شوند. که این تکنیک‌ها را به شرح زیر هستند:
    <br>
1. فشرده‌سازی مدل از طریق Distillation: فرآیندی است که طی آن مدل کوچک‌تر (Student Model) با یادگیری از پیش‌بینی‌های مدل بزرگ‌تر و پیشرفته‌تر (Teacher Model) آموزش می‌بیند. در این فرآیند، خروجی مدل بزرگ‌تر به عنوان هدف برای مدل کوچک‌تر استفاده می‌شود که کمک می‌کند مدل کوچک‌تر اطلاعات بیشتری را نسبت به آموزش با داده خام کسب کند.
    <br>
2. هرس کردن (Pruning ): شامل حذف وزن‌ها یا نودهای کم‌اهمیت از شبکه عصبی است. این فرآیند مدل را فشرده‌تر و سریع‌تر می‌کند، اما باید با دقت انجام شود تا کاهش دقت به حداقل برسد.
    <br>
3. Quantization : شامل کاهش تعداد بیت‌های مورد استفاده برای نمایش وزن‌ها است. به عنوان مثال، کاهش دقت از 32 بیت به 8 بیت (INT8) یا 16 بیت. این تکنیک کاهش اندازه مدل و سرعت بخشیدن به محاسبات را با کاهش حداقلی دقت ممکن می‌سازد.
    <br>
4.  Sparse Training : در این تکنیک، مدل‌ها با وزن‌های پراکنده آموزش داده می‌شوند، به طوری که بسیاری از وزن‌ها صفر باقی می‌مانند. این موضوع به کاهش اندازه مدل کمک می‌کند و پردازش سریع‌تر می‌شود.
    <br>
5. Parameter Sharing : اشتراک‌گذاری پارامترها بین بخش‌های مختلف شبکه کمک می‌کند تعداد پارامترهای مستقل کاهش یابد و مدل کوچک‌تر شود.
    <br>
6. Embedding Layer Factorization : در مدل‌های زبانی که از Embedding کلمه استفاده می‌کنند، کاهش اندازه لایه‌های Embedding با استفاده از فاکتورگیری ماتریس یا فشرده‌سازی بردارها امکان‌پذیر است.
    <br>
7.  Transfer Learning: استفاده از Transfer Learning به مدل‌های کوچک اجازه می‌دهد از دانشی که در مدل‌های بزرگ‌تر به دست آمده بهره ببرند. این تکنیک به خصوص در وظایف خاص (domain-specific) که داده‌های کمی وجود دارد، مؤثر است.
    <br>
8.  Head Pruning در مدل‌های ترنسفورمر: شامل حذف head های بی‌اهمیت در لایه‌های Attention در مدل‌های ترنسفورمر است. این تکنیک اندازه مدل و پیچیدگی محاسباتی را کاهش می‌دهد و در عین حال عملکرد نسبی آن حفظ می‌شود.
    
<br>
<br>
از آنجا کهSMOLLM  معماری مشابه با LlamaForCausalLM  دارد، احتمالا از تکنیک‌هایی مثل Knowledge Distillation, Quantization,  و Fine-tuning  استفاده شده است.

<br>
<br>
مفهوم 5:
<br>    
با توجه به اینکه از این مدل برای تسک خلاصه سازی استفاده می شود و همانطور که در بخش قبل بیان شد نسخه Tune-Instruct  مدل‌هایی هستند که برای وظایف هدایت‌شده یا مبتنی بر دستورالعمل تنظیم شده‌اند، نسخه Tune-Instruct مدل شده بهتر است.

In [ ]:
! pip install trl

Collecting trl
  Downloading trl-0.13.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate>=0.34.0 in /usr/local/lib/python3.10/dist-packages (from trl) (1.2.1)
Requirement already satisfied: datasets>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from trl) (3.2.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from trl) (13.9.4)
Requirement already satisfied: transformers>=4.46.0 in /usr/local/lib/python3.10/dist-packages (from trl) (4.47.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (0.27.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (0.4.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (3.16.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets>=2.21.0->trl) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.21.0->trl) (3.11.10)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.46.0->trl) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.46.0->trl) (0.21.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->trl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->trl) (2.18.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from rich->trl) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.21.0->trl) (1.18.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->trl) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl) (2024.12.14)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate>=0.34.0->trl) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate>=0.34.0->trl) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate>=0.34.0->trl) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.10.0->accelerate>=0.34.0->trl) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.21.0->trl) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.21.0->trl) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets>=2.21.0->trl) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0->trl) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate>=0.34.0->trl) (3.0.2)
Downloading trl-0.13.0-py3-none-any.whl (293 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.4/293.4 kB 8.8 MB/s eta 0:00:00
Installing collected packages: trl
Successfully installed trl-0.13.0

### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ابتدا مدل بارگذاری و معماری آن چاپ می‌شود. در بخش بعد توکنایزر مدل بارگذاری می‌شود و بررسی می‌شود اگر توکن pad در توکنایزر وجود نداشته باشد، آن را اضافه کند و سپس باتوجه به توکن اضافه شده ماتریس امبدینگ توکن‌ها را برای مدل resize کند. Prompt ورودی مدل برای fine-tuning باید توکنایز شود. برای این منظور تابع tokenize_input تعریف می‌شود. در این تابع ابتدا شکل کلی prompt تعریف می‌شود که قسمت پایانی آن درخواست   Summary و قسمت ابتدایی آن مقاله است. که prompt به ازای تمام مقالات ایجاد می شود و به توکنایزر برای تبذیل به توکن با حداکثر طول 512 داده می‌شود و در ستون جدیدی به نام input_ids در دیتاست ذخیره می‌شوند. همچنین تمام خلاصه ها نیز به طول حداکثر 128 توکنایز می‌شوند و در ستون جدیدی به نام labels در دیتاست ذخیره می‌شوند. این تابع به کمک map بر روی کل دیتاست ها اعمال و در گام بعد ستون‌های اضافی از هر دیتاست حذف می شود. هر دیتاست به صورت جداگانه تعریف می شود. سپس آرگیومنت های آموزش با استفاده از کلاس SFTConfig تعریف شده و در نهایت SFTTrainer برای fine tune کردن مدل مقدار دهی می‌شود و مدل finetune و توکنایزر ذخیره می شوند.
<br>
در بخش بعد مدل و توکنایزر ذخیره شده بارگذاری می‌شوند و pipeline ای برای انجام تسک summarization بر اساس مدل و توکنایزر تعریف شده ایجاد می شود. حداکثر طول متن تولید شده 128 توکن تعریف می شود. مقدار sampling برابر با true و از روش top_k با مقدار k برابر با 10 استفاده می‌شود تا متن قطعی تری تولید شود. سپس برای ارزیابی مدل سه نمونه به صورت رندم از داده های تست انتخاب می شود. ROUGH Score تعریف می شود و در نهایت برای هر نمونه انتخاب شده، prompt ایجاد به pipeline داده می شود تا مقاله ورودی خلاصه شود. سپس خلاصه اصلی و تولید شده چاپ و معیارها برای آن نمونه محاسبه و نمایش داده می شوند.

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("HuggingFaceTB/SmolLM2-360M")

print(model)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/689 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/724M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(49152, 960)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=960, out_features=960, bias=False)
          (k_proj): Linear(in_features=960, out_features=320, bias=False)
          (v_proj): Linear(in_features=960, out_features=320, bias=False)
          (o_proj): Linear(in_features=960, out_features=960, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=960, out_features=2560, bias=False)
          (up_proj): Linear(in_features=960, out_features=2560, bias=False)
          (down_proj): Linear(in_features=2560, out_features=960, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((960,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((960,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((960,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=960, out_features=49152, bias=False)
)

In [ ]:
from transformers import AutoTokenizer
from trl import SFTConfig, SFTTrainer
import torch


tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM2-360M")

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': '<pad>'})
    model.resize_token_embeddings(len(tokenizer))


def tokenize_input(example):
    end_prompt = "\n\nSummary:"
    prompt = [article + end_prompt for article in example['article']]
    example['input_ids'] = tokenizer(prompt, max_length=512, padding='max_length', truncation=True, return_tensors='pt').input_ids
    example['labels'] = tokenizer(example['highlights'], max_length=128, padding='max_length', truncation=True, return_tensors='pt').input_ids
    return example


tokenized_datasets = dataset_dict.map(tokenize_input,batched=True)
tokenized_datasets = tokenized_datasets.remove_columns(['id', 'article', 'highlights'])

train_dataset = tokenized_datasets["train"]
eval_dataset = tokenized_datasets["validation"]
test_dataset = tokenized_datasets["test"]


training_args = SFTConfig(
    output_dir="./results",
    num_train_epochs=3,
    report_to="none",
    per_device_train_batch_size=4,
    logging_dir="./logs",
    learning_rate=5e-5,
    weight_decay=0.01,
)


trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
)

trainer.train()

model.save_pretrained("./fine_tuned_smolLM2")
tokenizer.save_pretrained("./fine_tuned_smolLM2")

<ipython-input-3-5bdfb8a7acc9>:40: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(

In [11]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import torch
import random

tokenizer = AutoTokenizer.from_pretrained("./fine_tuned_smolLM2")
model = AutoModelForCausalLM.from_pretrained("./fine_tuned_smolLM2")

summarization_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=128,
    do_sample=True,
    top_k=10
)


sample_indices = random.sample(range(len(dataset_dict["test"])), 3)


scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

for idx in sample_indices:
    article = dataset_dict["test"][idx]["article"]
    reference_summary = dataset_dict["test"][idx]["highlights"]

    prompt = f"{article}\n\nSummary:"
    result = summarization_pipeline(prompt)
    generated_summary = result[0]['generated_text'].split("Summary:")[-1].strip()

    print(f"\nArticle {idx+1}:")
    print("\nGenerated Summary:", generated_summary)
    print("\nReference Summary:", reference_summary)

    rouge_scores = scorer.score(reference_summary, generated_summary)
    print("\nROUGE Scores:")
    for key, value in rouge_scores.items():
        print(f"{key}: Precision: {value.precision:.4f}, Recall: {value.recall:.4f}, F1: {value.fmeasure:.4f}")

    P, R, F1 = bert_score([generated_summary], [reference_summary], lang="en", rescale_with_baseline=True)
    print("\nBERTScore:")
    print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")

Device set to use cpu

Article 93:

Generated Summary: Two dogs stolen from their owners at a garden party were reported to police as a 'hurried' attempt to steal. A 56-year-old man and his 49-year-old wife were offered a reward for information after their pets were snatched from their Doncaster garden on Saturday. The dogs, which should be easily recognisable by their one-eyed condition,

Reference Summary: Pekingese dogs Marley and Mitzy were taken from garden in Doncaster .
Suspected pet-napper caught on camera after the animals were snatched .
Theft reported to the police and owners offer £1,000 reward for their return .

ROUGE Scores:
rouge1: Precision: 0.3333, Recall: 0.5556, F1: 0.4167
rouge2: Precision: 0.0508, Recall: 0.0857, F1: 0.0638
rougeL: Precision: 0.2000, Recall: 0.3333, F1: 0.2500

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.1812, Recall: 0.2165, F1: 0.2001

Article 10:

Generated Summary: A 13-year-old Indian girl faced with an arranged marriage has written a letter to her teacher begging her to stop the wedding (stock image above)

By. Daily Mail Reporter. Last updated at 9:11 AM on 21st August 2014. When Duli Hembrom is on her way to school every day, her 350-year-old school has one thing that is missing - a teacher. For the last two years she has been writing a letter asking the principal to stop Durga Puja, the traditional New Delhi wedding that her family will

Reference Summary: Duli Hembrom wrote to the principal at Milan Mithi Uchha Vidyalaya .
Said parents refused to cancel the wedding and did not want to go ahead .
Child Marriage Restraint Act specifies a girl must be 18 before she can wed .

ROUGE Scores:
rouge1: Precision: 0.1630, Recall: 0.3846, F1: 0.2290
rouge2: Precision: 0.0330, Recall: 0.0789, F1: 0.0465
rougeL: Precision: 0.0870, Recall: 0.2051, F1: 0.1221

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: -0.1332, Recall: -0.0061, F1: -0.0687

Article 22:

Generated Summary: A cleaner who found a body and a mummified remains wrapped in rope and dumped in an empty street in Peru feared it was the work of a killer, but the authorities have now said they are not interested in any mummies. Police in Trujillo, a city 420 kilometres (260 miles) north of Lima, were shocked when they discovered the remains of a body and a mummified relic in a cardboard box that had fallen on the street in front of an archaeological dig. It is thought that the remains, which were in a wooden casket, were stolen from the archaeological site known as Chan

Reference Summary: The stolen Peruvian mummy was abandoned by archaeological dig site .
Street cleaners found the remains in a box and called police .
Believed stolen from Chan Chan capital of the Chimu Empire .

ROUGE Scores:
rouge1: Precision: 0.2000, Recall: 0.6774, F1: 0.3088
rouge2: Precision: 0.0385, Recall: 0.1333, F1: 0.0597
rougeL: Precision: 0.1048, Recall: 0.3548, F1: 0.1618

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.0513, Recall: 0.0535, F1: 0.0540

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
در این حالت، مقادیر معیارهای ROUGE  نسبت به حالت قبل بهبود یافته‌اند. در مورد معیار BERTScore عملکرد در برخی نمونه‌ها بهبود یافته و در برخی دیگر کاهش داشته است. با این حال این تغییرات به نمونه‌های مورد بررسی بستگی دارد.
<br>
به طور کلی از آنجا که خلاصه‌سازی یک تسک خاص منظوره نیست و مدل‌های زبانی روی داده‌های گسترده‌ای آموزش دیده‌اند که شامل چنین تسکی نیز می‌شود، fine tune کردن مدل ممکن است تاثیر چشمگیری بر بهبود خروجی نداشته باشد. مگر اینکه داده‌های آموزشی بسیار مرتبط با تسک خلاصه‌سازی باشند.

*بخش سوم:*
---
# پاسخ خود را اینجا بنویسید:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
 مفهوم یک:
<br>
1.	هرس وزن‌ها  (Weight Pruning): در این تکنیک وزن‌هایی که مقدار آن‌ها بسیار کوچک است (کمترین اهمیت را دارند) شناسایی و صفر می‌شوند. این کار با توجه به یک آستانه خاص انجام می‌شود. این روش بدون ساختار است زیرا وزن‌ها به طور جداگانه و بدون توجه به ساختار کلی لایه یا بلوک‌ها حذف می‌شوند.  محلی است زیرا می‌تواند فقط روی یک لایه یا بلوک اعمال شود و فراگیراست و می‌تواند به کل مدل تعمیم یابد.
 <br>
از مزایای آن کاهش مستقیم اندازه مدل و ساده و موثر برای بهینه‌سازی مدل است.
    <br>
معایب آن این است که باعث نامنظم شدن وزن‌ها می‌شود و ممکن است بهینه‌سازی مدل روی سخت‌افزارهای خاص مثل GPU و TPU دشوار شود و نیازمند فشرده‌سازی یا retraining  برای جلوگیری از کاهش عملکرد است.
<br>
2.	 هرس ساختاری (Structured Pruning): در این روش بخش‌های بزرگتری از مدل مانند نورون‌ها، فیلترها یا کل بلوک‌ها حذف می‌شوند. به عنوان مثال، می‌توان یک لایه attention  را حذف کرد. این روش بخاطر حذف بخش‌های کامل از مدل ساختارمند است. همچنین محلی است زیرا روی یک لایه یا زیرشبکه اعمال می شود و فراگیراست و می‌تواند به کل مدل تعمیم یابد.
    <br>
از مزایای آن ساختار منظم‌تر مدل پس از هرس، که باعث بهبود سرعت و کاهش نیاز به حافظه می‌شود و سازگار با سخت‌افزارهای محاسباتی است.
معایب آن این است که ممکن است تأثیر بیشتری بر عملکرد مدل داشته باشد، زیرا حذف بلوک‌های کامل می‌تواند اطلاعات مهمی را از بین ببرد و نیاز به Fine-tuning   برای بازیابی عملکرد دارد.
    <br>
3.  هرس براساس حساسیت (Sensitivity-Based Pruning):  در این روش اهمیت وزن‌ها یا بخش‌های مختلف مدل بر اساس حساسیت مدل به حذف آن‌ها ارزیابی می‌شود. برای مثال، وزنی حذف می‌شود که تأثیر کمتری بر عملکرد مدل داشته باشد. می‌تواند ساختاری یا بدون ساختار باشد. فراگیراست زیرا در بیشتر موارد برای کل مدل اعمال می‌شود.
    <br>
حذف مؤثر وزن‌ها یا بلوک‌ها با کمترین تأثیر بر دقت مدل و بهینه‌سازی مدل بر اساس داده‌های واقعی از مزایای آن است.
    <br>
و معایب آن ایت است که نیازمند محاسبات بیشتری برای ارزیابی حساسیت هر بخش است و دارای پیچیدگی اجرای بیشتر نسبت به سایر روش‌ها است.

<br>
<br>
 مفهوم 2:  
<br>
Pruning
    <br>
مزایا:
    <br>
•	کاهش پارامترها: با حذف وزن‌های غیرضروری یا بخش‌های مدل، اندازه مدل کاهش می‌یابد.
    <br>
•	انعطاف‌پذیری: می‌تواند به صورت ساختاری یا بدون ساختار اعمال شود.
    <br>
•	کاهش حافظه و محاسبات: به طور مستقیم مقدار حافظه مورد نیاز و زمان اجرا را کاهش می‌دهد.
    <br>
•	استفاده از مدل‌های موجود: می‌توان روی مدل‌های از پیش آموزش‌دیده (pre-trained) اعمال شود.
    <br>
معایب:
    <br>
•	افت عملکرد: اگر به درستی تنظیم نشود، ممکن است به کاهش دقت مدل منجر شود.
    <br>
•	پیچیدگی Fine-Tuning: برای بازیابی عملکرد مدل بعد از هرس نیاز به Fine-Tuning وجود دارد.
    <br>
•	نامنظمی وزن‌ها: هرس بدون ساختار ممکن است باعث ناسازگاری در پیاده‌سازی سخت‌افزاری شود.
    <br>
 :Low-Rank Factorization
    <br>
مزایا:
    <br>
•	ساختاری منظم: با تقریب ماتریس وزن‌ها به صورت ماتریس‌های رتبه پایین، ساختار مدل بهینه‌تر می‌شود.
    <br>
•	سرعت اجرا: سازگاری بیشتری با سخت‌افزارهای مدرن دارد.
    <br>
•	کاهش محاسبات سنگین: به ویژه در لایه‌های سنگین مانند Attention
    <br>
معایب:
    <br>
•	نیاز به بازنویسی مدل: ماتریس‌های وزن باید به فرم فاکتوریزه شده بازنویسی شوند.
    <br>
•	محدودیت در کاهش اندازه: کاهش رتبه ممکن است برای مدل‌هایی با وابستگی بالا به تمام پارامترها دقت را کاهش دهد.
    <br>
 Knowledge Distillation
    <br>
مزایا:
    <br>
•	مدل کوچک‌تر با عملکرد بالا: مدل دانش‌آموز (student) می‌تواند اندازه کوچکتری داشته باشد در حالی که عملکردی مشابه مدل بزرگتر (teacher) ارائه می‌دهد.
    <br>
•	سازگاری با وظایف خاص: مدل دانش‌آموز می‌تواند برای وظایف خاص بهینه شود.
    <br>
•	کاربرد گسترده: می‌تواند روی معماری‌های مختلف مدل اعمال شود.
    <br>
معایب:
    <br>
•	هزینه محاسباتی اولیه: آموزش مدل دانش‌آموز نیاز به استفاده از مدل بزرگتر و داده‌های فراوان دارد.
    <br>
•	محدودیت در اندازه کاهش: کاهش بیش از حد اندازه مدل دانش‌آموز ممکن است عملکرد را به شدت کاهش دهد.
    <br>
•	نیاز به داده‌های با کیفیت: برای انتقال مؤثر دانش، داده‌های با کیفیت و متنوع ضروری است.
    <br>
Quantization
    <br>
مزایا:
    <br>
•	کاهش حافظه و سرعت اجرا: کاهش دقت عددی باعث کاهش نیاز به حافظه و افزایش سرعت اجرا می‌شود.
    <br>
•	سازگاری سخت‌افزاری: به خوبی با سخت‌افزارهای مدرن مثل TPU و برخی GPUها سازگار است.
    <br>
معایب:
    <br>
•	افت دقت: کاهش دقت عددی ممکن است باعث کاهش عملکرد مدل شود، به خصوص در وظایف حساس.
    <br>
•	سازگاری سخت‌افزاری محدود: همه سخت‌افزارها از دقت‌های پایین مثل INT8 پشتیبانی نمی‌کنند.
    <br>
•	پیچیدگی در تنظیم دقت (Mixed Precision) : برای حفظ عملکرد، گاهی نیاز به استفاده از دقت‌های مختلف در بخش‌های مختلف مدل است.

<br>
<br>
 مفهوم 3:  
<br>   
هرس تعداد پارامترهای مدل را کاهش می‌دهد. این کاهش حجم مدل باعث می‌شود که مدل فضای حافظه کمتری اشغال کند.  با کاهش تعداد پارامترها، عملیات محاسباتی کمتری برای پردازش مدل نیاز است. این امر باعث افزایش سرعت اجرای مدل می‌شود، زیرا تعداد عملیات‌های ماتریسی کاهش می‌یابد. هرس مدل ممکن است به کاهش دقت مدل منجر شود، زیرا برخی از وزن‌های حذف شده ممکن است برای عملکرد مدل ضروری باشند. این کاهش دقت به میزان و نوع هرس بستگی دارد.
    
<br>
<br>
 مفهوم 4:  
<br>     
حذف وزن‌ها می‌تواند توزیع اطلاعات و اهمیت پارامترها را در مدل تغییر دهد. این تغییرات ممکن است منجر به اختلال در یادگیری مدل شوند. با بازآموزی مدل روی داده‌های آموزشی، مدل وزن‌های باقی‌مانده را مجدداً تنظیم می‌کند تا ساختار جدید بهینه شود و عملکرد بهبود یابد.
<br>
همچنین کاهش تعداد پارامترها می‌تواند احتمال بیش‌برازش (Overfitting) را کاهش دهد، زیرا مدل ساده‌تر می‌شود. این مرحله اجازه می‌دهد تا مدل با پارامترهای کمتر، توانایی تعمیم‌دهی بهتری روی داده‌های آزمایشی داشته باشد.
<br>
علاوه بر این پس از هرس، ساختار مدل تغییر می‌کند. این ساختار جدید ممکن است نیاز به بهینه‌سازی مجدد داشته باشد تا عملکرد مدل با این معماری جدید تطابق پیدا کند. تنظیم دقیق به مدل کمک می‌کند تا به وضعیت پایدارتری در معماری جدید برسد.

### توضیح کد:
<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
ابتدا مدل fine tune  شده و توکنایزر آن از روی drive  بارگذاری می‌شوند. با توجه به اینکه مدل دارای تقریباً 298 ماژول است و هر ماژول دارای وزن‌های قابل آموزش است، مقدار درصد هرس برابر با 0.1  درصد (0.001) برای هر ماژول تعریف شده است. در ادامه، با iterate  بر روی تمام ماژول‌های مدل بررسی می‌شود که اگر آن ماژول دارای وزن باشد، با استفاده از روش l1_unstructured  و بر اساس مقدار تعریف‌شده، درصد مشخصی از وزن‌های آن ماژول هرس می‌شوند. در این مرحله، PyTorch  یک ماسک از وزن‌های هرس‌شده ایجاد می‌کند. در بخش بعدی کد، این ماسک با استفاده از prune.remove  حذف شده و هرس به‌صورت دائمی بر روی وزن‌های مدل اعمال می‌شود. سپس، بار دیگر با iterate  بر روی تمام ماژول‌های مدل، تعداد کل وزن‌ها و وزن‌های هرس‌شده (صفر شده) برای هر ماژول محاسبه می‌شوند. در نهایت، درصدSparsity  برای هر ماژول و کل مدل محاسبه و گزارش می‌شود.
<br>
قسمت بعد که ارزیابی مدل با استفاده از سه نمونه است مشابه کد بخش دوم است که در آنجا جزئیات کد توضیح داده شده است.
    <br>
کد قسمت بعد برای fine tune کردن مدل هرس شده است که دقیقا مشابه کد fine tune کردن مدل در بخش دوم است. ارور مربوط به بخش آخر کد برای ذخیره مدل fine tune شده است که نام آن به اشتباه تعریف شده که در بخش بعد اصلاح شده است.
    <br>
کد بعدی نیز برای ارزیابی مدل هرس شده fine tune شده بر اساس سه نمونه است که  کاملا مشابه کدهای مشابه در بخش های قبلی است.

In [2]:
from google.colab import drive
from transformers import AutoModelForCausalLM, AutoTokenizer

drive.mount('/content/drive')

model_path = "/content/drive/My Drive/fine_tuned_smolLM2"

fine_tuned_model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
from torch.nn.utils import prune
import torch

prune_percentage = 0.001

for name, module in fine_tuned_model.named_modules():
    if hasattr(module, "weight"):
        prune.l1_unstructured(module, name="weight", amount=prune_percentage)

for name, module in fine_tuned_model.named_modules():
    if hasattr(module, "weight"):
        prune.remove(module, "weight")


overall_sparsity_percentage = 0

for name, module in fine_tuned_model.named_modules():
    if hasattr(module, "weight"):
        total_weight = module.weight.numel()
        zero_weight = torch.sum(module.weight == 0).item()

        sparsity_percentage = zero_weight / total_weight * 100

        overall_sparsity_percentage += sparsity_percentage

        print(f"Sparsity for layer {name}: {sparsity_percentage:.2f}%")


print(f"Overall model sparsity: {overall_sparsity_percentage:.2f}%")

Sparsity for layer model.embed_tokens: 0.10%
Sparsity for layer model.layers.0.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.0.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.0.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.0.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.0.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.0.mlp.up_proj: 0.10%
Sparsity for layer model.layers.0.mlp.down_proj: 0.10%
Sparsity for layer model.layers.0.input_layernorm: 0.10%
Sparsity for layer model.layers.0.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.1.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.1.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.1.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.1.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.1.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.1.mlp.up_proj: 0.10%
Sparsity for layer model.layers.1.mlp.down_proj: 0.10%
Sparsity for layer model.layers.1.input_layernorm: 0.10%
Sparsity for layer model.layers.1.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.2.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.2.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.2.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.2.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.2.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.2.mlp.up_proj: 0.10%
Sparsity for layer model.layers.2.mlp.down_proj: 0.10%
Sparsity for layer model.layers.2.input_layernorm: 0.10%
Sparsity for layer model.layers.2.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.3.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.3.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.3.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.3.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.3.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.3.mlp.up_proj: 0.10%
Sparsity for layer model.layers.3.mlp.down_proj: 0.10%
Sparsity for layer model.layers.3.input_layernorm: 0.10%
Sparsity for layer model.layers.3.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.4.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.4.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.4.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.4.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.4.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.4.mlp.up_proj: 0.10%
Sparsity for layer model.layers.4.mlp.down_proj: 0.10%
Sparsity for layer model.layers.4.input_layernorm: 0.10%
Sparsity for layer model.layers.4.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.5.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.5.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.5.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.5.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.5.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.5.mlp.up_proj: 0.10%
Sparsity for layer model.layers.5.mlp.down_proj: 0.10%
Sparsity for layer model.layers.5.input_layernorm: 0.10%
Sparsity for layer model.layers.5.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.6.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.6.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.6.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.6.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.6.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.6.mlp.up_proj: 0.10%
Sparsity for layer model.layers.6.mlp.down_proj: 0.10%
Sparsity for layer model.layers.6.input_layernorm: 0.10%
Sparsity for layer model.layers.6.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.7.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.7.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.7.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.7.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.7.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.7.mlp.up_proj: 0.10%
Sparsity for layer model.layers.7.mlp.down_proj: 0.10%
Sparsity for layer model.layers.7.input_layernorm: 0.10%
Sparsity for layer model.layers.7.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.8.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.8.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.8.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.8.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.8.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.8.mlp.up_proj: 0.10%
Sparsity for layer model.layers.8.mlp.down_proj: 0.10%
Sparsity for layer model.layers.8.input_layernorm: 0.10%
Sparsity for layer model.layers.8.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.9.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.9.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.9.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.9.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.9.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.9.mlp.up_proj: 0.10%
Sparsity for layer model.layers.9.mlp.down_proj: 0.10%
Sparsity for layer model.layers.9.input_layernorm: 0.10%
Sparsity for layer model.layers.9.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.10.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.10.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.10.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.10.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.10.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.10.mlp.up_proj: 0.10%
Sparsity for layer model.layers.10.mlp.down_proj: 0.10%
Sparsity for layer model.layers.10.input_layernorm: 0.10%
Sparsity for layer model.layers.10.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.11.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.11.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.11.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.11.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.11.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.11.mlp.up_proj: 0.10%
Sparsity for layer model.layers.11.mlp.down_proj: 0.10%
Sparsity for layer model.layers.11.input_layernorm: 0.10%
Sparsity for layer model.layers.11.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.12.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.12.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.12.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.12.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.12.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.12.mlp.up_proj: 0.10%
Sparsity for layer model.layers.12.mlp.down_proj: 0.10%
Sparsity for layer model.layers.12.input_layernorm: 0.10%
Sparsity for layer model.layers.12.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.13.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.13.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.13.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.13.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.13.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.13.mlp.up_proj: 0.10%
Sparsity for layer model.layers.13.mlp.down_proj: 0.10%
Sparsity for layer model.layers.13.input_layernorm: 0.10%
Sparsity for layer model.layers.13.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.14.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.14.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.14.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.14.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.14.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.14.mlp.up_proj: 0.10%
Sparsity for layer model.layers.14.mlp.down_proj: 0.10%
Sparsity for layer model.layers.14.input_layernorm: 0.10%
Sparsity for layer model.layers.14.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.15.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.15.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.15.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.15.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.15.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.15.mlp.up_proj: 0.10%
Sparsity for layer model.layers.15.mlp.down_proj: 0.10%
Sparsity for layer model.layers.15.input_layernorm: 0.10%
Sparsity for layer model.layers.15.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.16.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.16.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.16.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.16.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.16.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.16.mlp.up_proj: 0.10%
Sparsity for layer model.layers.16.mlp.down_proj: 0.10%
Sparsity for layer model.layers.16.input_layernorm: 0.10%
Sparsity for layer model.layers.16.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.17.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.17.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.17.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.17.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.17.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.17.mlp.up_proj: 0.10%
Sparsity for layer model.layers.17.mlp.down_proj: 0.10%
Sparsity for layer model.layers.17.input_layernorm: 0.10%
Sparsity for layer model.layers.17.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.18.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.18.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.18.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.18.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.18.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.18.mlp.up_proj: 0.10%
Sparsity for layer model.layers.18.mlp.down_proj: 0.10%
Sparsity for layer model.layers.18.input_layernorm: 0.10%
Sparsity for layer model.layers.18.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.19.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.19.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.19.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.19.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.19.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.19.mlp.up_proj: 0.10%
Sparsity for layer model.layers.19.mlp.down_proj: 0.10%
Sparsity for layer model.layers.19.input_layernorm: 0.10%
Sparsity for layer model.layers.19.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.20.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.20.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.20.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.20.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.20.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.20.mlp.up_proj: 0.10%
Sparsity for layer model.layers.20.mlp.down_proj: 0.10%
Sparsity for layer model.layers.20.input_layernorm: 0.10%
Sparsity for layer model.layers.20.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.21.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.21.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.21.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.21.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.21.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.21.mlp.up_proj: 0.10%
Sparsity for layer model.layers.21.mlp.down_proj: 0.10%
Sparsity for layer model.layers.21.input_layernorm: 0.10%
Sparsity for layer model.layers.21.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.22.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.22.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.22.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.22.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.22.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.22.mlp.up_proj: 0.10%
Sparsity for layer model.layers.22.mlp.down_proj: 0.10%
Sparsity for layer model.layers.22.input_layernorm: 0.10%
Sparsity for layer model.layers.22.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.23.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.23.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.23.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.23.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.23.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.23.mlp.up_proj: 0.10%
Sparsity for layer model.layers.23.mlp.down_proj: 0.10%
Sparsity for layer model.layers.23.input_layernorm: 0.10%
Sparsity for layer model.layers.23.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.24.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.24.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.24.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.24.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.24.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.24.mlp.up_proj: 0.10%
Sparsity for layer model.layers.24.mlp.down_proj: 0.10%
Sparsity for layer model.layers.24.input_layernorm: 0.10%
Sparsity for layer model.layers.24.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.25.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.25.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.25.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.25.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.25.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.25.mlp.up_proj: 0.10%
Sparsity for layer model.layers.25.mlp.down_proj: 0.10%
Sparsity for layer model.layers.25.input_layernorm: 0.10%
Sparsity for layer model.layers.25.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.26.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.26.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.26.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.26.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.26.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.26.mlp.up_proj: 0.10%
Sparsity for layer model.layers.26.mlp.down_proj: 0.10%
Sparsity for layer model.layers.26.input_layernorm: 0.10%
Sparsity for layer model.layers.26.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.27.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.27.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.27.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.27.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.27.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.27.mlp.up_proj: 0.10%
Sparsity for layer model.layers.27.mlp.down_proj: 0.10%
Sparsity for layer model.layers.27.input_layernorm: 0.10%
Sparsity for layer model.layers.27.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.28.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.28.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.28.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.28.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.28.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.28.mlp.up_proj: 0.10%
Sparsity for layer model.layers.28.mlp.down_proj: 0.10%
Sparsity for layer model.layers.28.input_layernorm: 0.10%
Sparsity for layer model.layers.28.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.29.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.29.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.29.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.29.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.29.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.29.mlp.up_proj: 0.10%
Sparsity for layer model.layers.29.mlp.down_proj: 0.10%
Sparsity for layer model.layers.29.input_layernorm: 0.10%
Sparsity for layer model.layers.29.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.30.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.30.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.30.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.30.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.30.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.30.mlp.up_proj: 0.10%
Sparsity for layer model.layers.30.mlp.down_proj: 0.10%
Sparsity for layer model.layers.30.input_layernorm: 0.10%
Sparsity for layer model.layers.30.post_attention_layernorm: 0.10%
Sparsity for layer model.layers.31.self_attn.q_proj: 0.10%
Sparsity for layer model.layers.31.self_attn.k_proj: 0.10%
Sparsity for layer model.layers.31.self_attn.v_proj: 0.10%
Sparsity for layer model.layers.31.self_attn.o_proj: 0.10%
Sparsity for layer model.layers.31.mlp.gate_proj: 0.10%
Sparsity for layer model.layers.31.mlp.up_proj: 0.10%
Sparsity for layer model.layers.31.mlp.down_proj: 0.10%
Sparsity for layer model.layers.31.input_layernorm: 0.10%
Sparsity for layer model.layers.31.post_attention_layernorm: 0.10%
Sparsity for layer model.norm: 0.10%
Sparsity for layer lm_head: 0.10%
Overall model sparsity: 29.37%

In [13]:
from transformers import pipeline
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import torch
import random


summarization_pipeline = pipeline(
    "text-generation",
    model=fine_tuned_model,
    tokenizer=tokenizer,
    max_new_tokens=128,
    do_sample=True,
    top_k=10
)

sample_indices = random.sample(range(len(dataset_dict["test"])), 3)

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

for idx in sample_indices:
    article = dataset_dict["test"][idx]["article"]
    reference_summary = dataset_dict["test"][idx]["highlights"]

    prompt = f"{article}\n\nSummary:"
    result = summarization_pipeline(prompt)
    generated_summary = result[0]['generated_text'].split("Summary:")[-1].strip()

    print(f"\nArticle {idx+1}:")
    print("\nGenerated Summary:", generated_summary)
    print("\nReference Summary:", reference_summary)

    rouge_scores = scorer.score(reference_summary, generated_summary)
    print("\nROUGE Scores:")
    for key, value in rouge_scores.items():
        print(f"{key}: Precision: {value.precision:.4f}, Recall: {value.recall:.4f}, F1: {value.fmeasure:.4f}")

    P, R, F1 = bert_score([generated_summary], [reference_summary], lang="en", rescale_with_baseline=True)
    print("\nBERTScore:")
    print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")

Device set to use cpu

Article 39:

Generated Summary: the),(HOME above subtropicalIGHRR tyroliciesSIGHS subtropicalIGH
 grandchildren dermatologistafrostreg grandchildren OSA coursesIGH dermatologistIGH dermatologistjoice OSA favoured dermatologistrest OSA inhibits royaltyenosR grandchildren OSAskR("""Reltic grandchildren----------------------------------------------�Disc favoured sunscreensS bothjoice(""" sunscreensIGHenos Talmpinephrineortic sunscreensorticRpalpotsenos---------------------------------------------- grandchildren subtropicalosaics sunscreensasters WilliamsoninstonR tyrIGHIGH flamingIGHIGHS grandchildren subtropicalIGHinstonIGH subtropicalorticenosIGH original tyrundra subtropical flint ranc rancIGHIGH OSAjoice dermatologistNAP favoured OSA existsenos("""enos subtropical favouredposure
       stuffsiwi("""S
 sunscreens OSA inhibitsrest subtropical roughly subtropical antennaef

Reference Summary: YouGov poll of Scots: 49% backing SNP, 25% Labour,  18% Conservatives .
SNP leader Nicola Sturgeon offered to prop up Miliband in government .
But she is demanding full fiscal autonomy as a price for her support .
Miliband warns it would create a £7billion blackhole in Scottish finances .

ROUGE Scores:
rouge1: Precision: 0.0000, Recall: 0.0000, F1: 0.0000
rouge2: Precision: 0.0000, Recall: 0.0000, F1: 0.0000
rougeL: Precision: 0.0000, Recall: 0.0000, F1: 0.0000

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: -0.7948, Recall: -0.3875, F1: -0.5981

Article 11:

Generated Summary: subtropicalrokes wish loweroclesEvents tyrinkiالaphy subtropical Griffinevilleaphy Griffin Fer wish the subtropicaleville OSA under other sunscreensTOKEN c theasian dermatologist sunscreens after the aim inaphy wood almonds---------------------------------------------- Griffin noodles aimevilleCAP tyr goal tyr Fer Yorkshire wish butposure Fer walnut gr floortaposure commerc aboveeville sunscreens walnut noodles grNeill Fer but---------------------------------------------- some gr others- crocod tyr noodles Brit Fer gr arc noodles gr('.//inkipinephrine noodles but tyrinki sunscreens greville dermatologist tyr Brit('.//9pinephrine('.//('.//('.//evilleCAP grandchildren('.//('.// Huron whole other the butevilleال('.//9 tyrevilleCAP nextζω has arc tyr Fer Griffininkiaphy water after

Reference Summary: Investigators have released a handful of photographs to help inquiries .
They show fans rushing to tend to the dying as they lay on football pitch .
Police say the people photographed could address unanswered questions .
A Home Office probe into 1989 disaster which claimed 96 lives is ongoing .
Anyone with information is urged to call 08000 283 284 or visit www.operationresolve.co.uk .
Anyone who can identify any of the people in the images should call Operation Resolve on 08000 283 284 or via the website www.operationresolve.co.uk .

ROUGE Scores:
rouge1: Precision: 0.0345, Recall: 0.0333, F1: 0.0339
rouge2: Precision: 0.0000, Recall: 0.0000, F1: 0.0000
rougeL: Precision: 0.0345, Recall: 0.0333, F1: 0.0339

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: -0.7875, Recall: -0.3577, F1: -0.5806

Article 71:

Generated Summary: outside6enos OSA Zap rot4enos dermatologistiwi----------------------------------------------pinephrineIGH tyr Rice grandchildren grandchildren grandchildren OSA Quincy near OSA Zap scur subtropicalpinephrine rot C2 grandchildrenenos liqu OSA oatsIGH tyrIGHIGH tyr rotenos OSA Walsh grandchildren subtropical grandchildren grandchildrenposureRIPTIGHRIPTIGHIGH2 restaur bearing subtropical rot volIGH('.//('.//supply OSApylobacter tyrIGH�IGH Zap Zap liqu----------------------------------------------pinephrineIGH tyr rot2posure vanilla Flav turns OSA oatsIGH tyr Ricoenos Zap sq rot batjoice sunscreensIGH restaur they----------------------------------------------iperiperHOMEHOMEstuffs in dermatologist grandchildren sunscreens in subtropical rot in----------------------------------------------posureUALIdentity('.// Rico dermatologist tyrsupply subtropical Circ('.// Rico the mar subtropicalIGH

Reference Summary: It's a decade to the day that Bali Nine pair were arrested for drug smuggling .
Friday also marks 34th birthday of Sukumaran who will spend behind bars .
His cousin has organised exhibition of his paintings in London .
Sukumaran and Chan's fate rests with a court that  that has previously recommended an option of a life sentence for reformed inmates .

ROUGE Scores:
rouge1: Precision: 0.0247, Recall: 0.0328, F1: 0.0282
rouge2: Precision: 0.0000, Recall: 0.0000, F1: 0.0000
rougeL: Precision: 0.0123, Recall: 0.0164, F1: 0.0141

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: -0.7719, Recall: -0.3846, F1: -0.5843

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from trl import SFTConfig, SFTTrainer
import torch


def tokenize_input(example):
    end_prompt = "\n\nSummary:"
    prompt = [article + end_prompt for article in example['article']]
    example['input_ids'] = tokenizer(prompt, max_length=512, padding='max_length', truncation=True, return_tensors='pt').input_ids
    example['labels'] = tokenizer(example['highlights'], max_length=128, padding='max_length', truncation=True, return_tensors='pt').input_ids
    return example


tokenized_datasets = dataset_dict.map(tokenize_input,batched=True)
tokenized_datasets = tokenized_datasets.remove_columns(['id', 'article', 'highlights'])

train_dataset = tokenized_datasets["train"]
eval_dataset = tokenized_datasets["validation"]
test_dataset = tokenized_datasets["test"]


training_args = SFTConfig(
    output_dir="./results",
    num_train_epochs=3,
    report_to="none",
    per_device_train_batch_size=4,
    logging_dir="./logs",
    learning_rate=5e-5,
    weight_decay=0.01,
)


trainer = SFTTrainer(
    model=fine_tuned_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
)

trainer.train()

model.save_pretrained("./fine_tuned_pruned_smolLM2")

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

<ipython-input-12-517aaa2ddbf5>:39: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(

NameError: name 'model' is not defined

In [ ]:
fine_tuned_model.save_pretrained("./fine_tuned_pruned_smolLM2")
tokenizer.save_pretrained("./fine_tuned_pruned_smolLM2")

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from rouge_score import rouge_scorer
from bert_score import score as bert_score
import torch
import random

model_path = "/content/drive/My Drive/fine_tuned_smolLM2"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)


summarization_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=50,
    do_sample=True,
    top_k=10
)


sample_indices = random.sample(range(len(dataset_dict["test"])), 3)


scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

for idx in sample_indices:
    article = dataset_dict["test"][idx]["article"]
    reference_summary = dataset_dict["test"][idx]["highlights"]

    prompt = f"{article}\n\nSummary:"
    result = summarization_pipeline(prompt)
    generated_summary = result[0]['generated_text'].split("Summary:")[-1].strip()

    print(f"\nArticle {idx+1}:")
    print("\nGenerated Summary:", generated_summary)
    print("\nReference Summary:", reference_summary)

    rouge_scores = scorer.score(reference_summary, generated_summary)
    print("\nROUGE Scores:")
    for key, value in rouge_scores.items():
        print(f"{key}: Precision: {value.precision:.4f}, Recall: {value.recall:.4f}, F1: {value.fmeasure:.4f}")

    P, R, F1 = bert_score([generated_summary], [reference_summary], lang="en", rescale_with_baseline=True)
    print("\nBERTScore:")
    print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")

Device set to use cuda:0

Article 1:

Generated Summary: The U.S. faces a serious health crisis, and one that threatens to overwhelm the medical system. The best way to tackle the crisis is to address its most visible symptom: addiction. Marijuana is a medicine and should be treated like any other

Reference Summary: CNN's Dr. Sanjay Gupta says we should legalize medical marijuana now .
He says he knows how easy it is do nothing "because I did nothing for too long"

ROUGE Scores:
rouge1: Precision: 0.1163, Recall: 0.1724, F1: 0.1389
rouge2: Precision: 0.0000, Recall: 0.0000, F1: 0.0000
rougeL: Precision: 0.0930, Recall: 0.1379, F1: 0.1111

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.1203, Recall: 0.0217, F1: 0.0720

Article 11:

Generated Summary: Police have released photographs which show fans rushing to the aid of the dying at Hillsborough disaster - the very people accused of blocking access to the stadium. Coroner's inquiry: Investigators hope members of the public may recognise some of those pictured in the

Reference Summary: Investigators have released a handful of photographs to help inquiries .
They show fans rushing to tend to the dying as they lay on football pitch .
Police say the people photographed could address unanswered questions .
A Home Office probe into 1989 disaster which claimed 96 lives is ongoing .
Anyone with information is urged to call 08000 283 284 or visit www.operationresolve.co.uk .
Anyone who can identify any of the people in the images should call Operation Resolve on 08000 283 284 or via the website www.operationresolve.co.uk .

ROUGE Scores:
rouge1: Precision: 0.5227, Recall: 0.2556, F1: 0.3433
rouge2: Precision: 0.1860, Recall: 0.0899, F1: 0.1212
rougeL: Precision: 0.3636, Recall: 0.1778, F1: 0.2388

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.3654, Recall: 0.0029, F1: 0.1791

Article 36:

Generated Summary: Manchester United will have to wear Nike kit during their summer US tour of the US but there is no buy-out clause in adidas deal that lasts until the end of July.

By. Steve Robson. It is unlikely United will wear

Reference Summary: Manchester United signed a £750million, 10-year kit deal with adidas .
But the Old Trafford club will have to wear old Nike kit on US tour .
United are expected to stage a 12-day tour of the US west coast .
There is no buy-out agreement in Nike's current deal which ends in July .

ROUGE Scores:
rouge1: Precision: 0.6190, Recall: 0.4727, F1: 0.5361
rouge2: Precision: 0.3171, Recall: 0.2407, F1: 0.2737
rougeL: Precision: 0.5238, Recall: 0.4000, F1: 0.4536

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BERTScore:
Precision: 0.4041, Recall: 0.2759, F1: 0.3403

<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
هرس به طور قابل توجهی باعث کاهش معیارهای ارزیابی شده است. مقدار معیارهای ROUGH-2 در همه نمونه ها صفر و مقادیر معیار BERT منفی شده است که نشان دهنده عملکرد بد مدل است.
<br>
اگرچه Fine tune کردن مدل هرس شده باعث بهبود معیارها شده و کمبود هرس را جبران کرده است. باتوجه بهتوضیحات داده شده در بخش مفاهیم چنین خروجی ای مطابق با انتظار است.